export enum TipoNotificacion {
  TURNO_RESERVADO = 'TURNO_RESERVADO',
  TURNO_CONFIRMADO = 'TURNO_CONFIRMADO',
  TURNO_CANCELADO = 'TURNO_CANCELADO',
  TURNO_REPROGRAMADO = 'TURNO_REPROGRAMADO',
  CHECK_IN = 'CHECK_IN',
  TURNO_AUSENTE = 'TURNO_AUSENTE',
  TURNO_AUSENTE_AUTO = 'TURNO_AUSENTE_AUTO',
  TURNO_AVISO_LLEGADA_TARDE = 'TURNO_AVISO_LLEGADA_TARDE',
  TURNO_INASISTENCIA_AVISO = 'TURNO_INASISTENCIA_AVISO',
  PLAN_CREADO = 'PLAN_CREADO',
  PLAN_EDITADO = 'PLAN_EDITADO',
  PLAN_ELIMINADO = 'PLAN_ELIMINADO',
  CONSULTA_FINALIZADA = 'CONSULTA_FINALIZADA',
  CONSULTA_PREAVISO_CIERRE_AUTO = 'CONSULTA_PREAVISO_CIERRE_AUTO',
  CONSULTA_CERRADA_AUTO = 'CONSULTA_CERRADA_AUTO',
  NUTRICIONISTA_DESACTIVADO = 'NUTRICIONISTA_DESACTIVADO',
  SOCIO_DESACTIVADO = 'SOCIO_DESACTIVADO',
  // === Reservados por el spec `crear-turno-en-nombre-del-socio-endpoint.md` ===
  // Se exponen en el enum por consistencia con el spec y paridad con
  // `packages/shared/src/types/notificacion.ts`, pero el use-case
  // `CrearTurnoEnNombreDeSocioUseCase` emite `TURNO_RESERVADO` con
  // `metadata.creadoPor` (decision documentada en design.md §11.H).
  // Mantenerlos reservados para una iteracion futura que quiera
  // discriminacion fina por rol emisor.
  TURNO_CREADO_POR_RECEPCION = 'TURNO_CREADO_POR_RECEPCION',
  TURNO_CREADO_POR_ADMIN = 'TURNO_CREADO_POR_ADMIN',
  TURNO_CREADO_POR_NUTRICIONISTA = 'TURNO_CREADO_POR_NUTRICIONISTA',
}
