export enum NivelFormacion {
  GRADO = 'GRADO',
  POSGRADO = 'POSGRADO',
  MAESTRIA = 'MAESTRIA',
  DOCTORADO = 'DOCTORADO',
  ESPECIALIZACION = 'ESPECIALIZACION',
  DIPLOMATURA = 'DIPLOMATURA',
  CURSO = 'CURSO',
}
