import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { NUTRICIONISTA_REPOSITORY } from 'src/domain/entities/Persona/Nutricionista/nutricionista.repository';
import { AppLoggerModule } from 'src/infrastructure/common/logger/app-logger.module';
import {
  AgendaOrmEntity,
  AlergiaOrmEntity,
  FichaSaludOrmEntity,
  MedicionOrmEntity,
  NutricionistaOrmEntity,
  ObservacionClinicaOrmEntity,
  PatologiaOrmEntity,
  SocioOrmEntity,
  TurnoOrmEntity,
  UsuarioOrmEntity,
} from 'src/infrastructure/persistence/typeorm/entities';
import { NutricionistaRepositoryImplementation } from 'src/infrastructure/persistence/typeorm/repositories/nutricionista.repository';
import {
  AsignarTurnoManualUseCase,
  BloquearTurnoUseCase,
  CancelarTurnoSocioUseCase,
  CheckInTurnoUseCase,
  ConfirmarTurnoSocioUseCase,
  DesbloquearTurnoUseCase,
  FinalizarConsultaUseCase,
  GetAgendaDiariaUseCase,
  GetFichaSaludPacienteUseCase,
  GetFichaSaludSocioUseCase,
  GetHistorialConsultasPacienteUseCase,
  GetHistorialMedicionesUseCase,
  GetResumenProgresoUseCase,
  GetTurnosDelDiaUseCase,
  GetTurnosRecepcionDiaUseCase,
  GetTurnoByIdUseCase,
  GuardarMedicionesUseCase,
  GuardarObservacionesUseCase,
  IniciarConsultaUseCase,
  ListMisTurnosUseCase,
  ListPacientesProfesionalUseCase,
  ReprogramarTurnoSocioUseCase,
  RegistrarAsistenciaTurnoUseCase,
  ReservarTurnoSocioUseCase,
  UpsertFichaSaludSocioUseCase,
} from './use-cases';

@Module({
  imports: [
    TypeOrmModule.forFeature([
      AgendaOrmEntity,
      AlergiaOrmEntity,
      FichaSaludOrmEntity,
      MedicionOrmEntity,
      NutricionistaOrmEntity,
      ObservacionClinicaOrmEntity,
      PatologiaOrmEntity,
      SocioOrmEntity,
      TurnoOrmEntity,
      UsuarioOrmEntity,
    ]),
    AppLoggerModule,
  ],
  providers: [
    AsignarTurnoManualUseCase,
    BloquearTurnoUseCase,
    CancelarTurnoSocioUseCase,
    CheckInTurnoUseCase,
    ConfirmarTurnoSocioUseCase,
    DesbloquearTurnoUseCase,
    FinalizarConsultaUseCase,
    GetAgendaDiariaUseCase,
    GetFichaSaludPacienteUseCase,
    GetFichaSaludSocioUseCase,
    GetHistorialConsultasPacienteUseCase,
    GetHistorialMedicionesUseCase,
    GetResumenProgresoUseCase,
    GetTurnosDelDiaUseCase,
    GetTurnosRecepcionDiaUseCase,
    GetTurnoByIdUseCase,
    GuardarMedicionesUseCase,
    GuardarObservacionesUseCase,
    IniciarConsultaUseCase,
    ListMisTurnosUseCase,
    ListPacientesProfesionalUseCase,
    ReprogramarTurnoSocioUseCase,
    RegistrarAsistenciaTurnoUseCase,
    ReservarTurnoSocioUseCase,
    UpsertFichaSaludSocioUseCase,
    {
      provide: NUTRICIONISTA_REPOSITORY,
      useClass: NutricionistaRepositoryImplementation,
    },
  ],
  exports: [
    AsignarTurnoManualUseCase,
    BloquearTurnoUseCase,
    CancelarTurnoSocioUseCase,
    CheckInTurnoUseCase,
    ConfirmarTurnoSocioUseCase,
    DesbloquearTurnoUseCase,
    FinalizarConsultaUseCase,
    GetAgendaDiariaUseCase,
    GetFichaSaludPacienteUseCase,
    GetFichaSaludSocioUseCase,
    GetHistorialConsultasPacienteUseCase,
    GetHistorialMedicionesUseCase,
    GetResumenProgresoUseCase,
    GetTurnosDelDiaUseCase,
    GetTurnosRecepcionDiaUseCase,
    GetTurnoByIdUseCase,
    GuardarMedicionesUseCase,
    GuardarObservacionesUseCase,
    IniciarConsultaUseCase,
    ListMisTurnosUseCase,
    ListPacientesProfesionalUseCase,
    ReprogramarTurnoSocioUseCase,
    RegistrarAsistenciaTurnoUseCase,
    ReservarTurnoSocioUseCase,
    UpsertFichaSaludSocioUseCase,
  ],
})
export class TurnosModule {}
