import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { AppLoggerModule } from 'src/infrastructure/common/logger/app-logger.module';
import {
  AgendaOrmEntity,
  AlergiaOrmEntity,
  FichaSaludOrmEntity,
  FichaSaludVersionOrmEntity,
  FotoProgresoOrmEntity,
  MedicionOrmEntity,
  NutricionistaOrmEntity,
  ObjetivoOrmEntity,
  ObservacionClinicaOrmEntity,
  PatologiaOrmEntity,
  PlanAlimentacionOrmEntity,
  SocioOrmEntity,
  TurnoConfirmacionTokenOrmEntity,
  TurnoOrmEntity,
  UsuarioOrmEntity,
} from 'src/infrastructure/persistence/typeorm/entities';
import { RepositoriesModule } from 'src/infrastructure/persistence/typeorm/repositories/repositories.module';
import {
  AbrirFichaDesdeTurnoUseCase,
  ActualizarMedicionUseCase,
  AsignarTurnoManualUseCase,
  AvisoLlegadaTardeUseCase,
  BloquearTurnoUseCase,
  CancelarTurnoSocioUseCase,
  CheckInTurnoUseCase,
  ConfirmarTurnoSocioUseCase,
  CrearTurnoEnNombreDeSocioUseCase,
  DesbloquearTurnoUseCase,
  EditarFichaPacienteNutricionistaUseCase,
  FinalizarConsultaPorInactividadUseCase,
  FinalizarConsultaUseCase,
  GetAgendaDiariaUseCase,
  GetFichaSaludPacienteUseCase,
  GetFichaSaludSocioUseCase,
  GetHistorialConsultasPacienteUseCase,
  GetHistorialMedicionesUseCase,
  GetHistorialTurnosPacienteUseCase,
  GetReporteEvolucionPacienteUseCase,
  GetResumenProgresoUseCase,
  GetTurnosDelDiaUseCase,
  GetTurnosRecepcionDiaUseCase,
  GetTurnoByIdUseCase,
  GetTurnoSocioByIdUseCase,
  GuardarMedicionesUseCase,
  GuardarObservacionesUseCase,
  IniciarConsultaUseCase,
  ListarHistorialFichaSaludNutricionistaUseCase,
  ListarHistorialFichaSaludSocioUseCase,
  ListMisTurnosUseCase,
  ListPacientesProfesionalUseCase,
  MarcarAusenteManualUseCase,
  NotificarSocioInasistenciaUseCase,
  ObtenerVersionFichaSaludNutricionistaUseCase,
  ObtenerVersionFichaSaludSocioUseCase,
  ReprogramarTurnoSocioUseCase,
  RegistrarAsistenciaTurnoUseCase,
  ReservarTurnoSocioUseCase,
  RevertirAusenteTurnoUseCase,
  ReabrirConsultaCerradaAutoUseCase,
  RevertirCheckinTurnoUseCase,
  UpsertFichaSaludSocioUseCase,
} from './use-cases';
import { SlotComputationService } from './services/slot-computation.service';
import { ValidacionesCreacionTurno } from './helpers/validaciones-creacion-turno.helper';
import { AuditoriaModule } from 'src/infrastructure/services/auditoria/auditoria.module';
import { AdjuntoClinicoModule } from 'src/infrastructure/services/adjunto-clinico/adjunto-clinico.module';
import { NotificacionesService } from 'src/application/notificaciones/notificaciones.service';
import { NotificacionOrmEntity } from 'src/infrastructure/persistence/typeorm/entities/notificacion.entity';
import { EmailModule } from 'src/application/email/email.module';

@Module({
  imports: [
    TypeOrmModule.forFeature([
      AgendaOrmEntity,
      AlergiaOrmEntity,
      FichaSaludOrmEntity,
      FichaSaludVersionOrmEntity,
      FotoProgresoOrmEntity,
      MedicionOrmEntity,
      NutricionistaOrmEntity,
      ObservacionClinicaOrmEntity,
      PatologiaOrmEntity,
      SocioOrmEntity,
      TurnoConfirmacionTokenOrmEntity,
      TurnoOrmEntity,
      UsuarioOrmEntity,
      NotificacionOrmEntity,
      ObjetivoOrmEntity,
      PlanAlimentacionOrmEntity,
    ]),
    RepositoriesModule,
    AppLoggerModule,
    AuditoriaModule,
    AdjuntoClinicoModule,
    EmailModule,
  ],
  providers: [
    AbrirFichaDesdeTurnoUseCase,
    ActualizarMedicionUseCase,
    AsignarTurnoManualUseCase,
    AvisoLlegadaTardeUseCase,
    BloquearTurnoUseCase,
    CancelarTurnoSocioUseCase,
    CheckInTurnoUseCase,
    ConfirmarTurnoSocioUseCase,
    CrearTurnoEnNombreDeSocioUseCase,
    DesbloquearTurnoUseCase,
    EditarFichaPacienteNutricionistaUseCase,
    FinalizarConsultaPorInactividadUseCase,
    FinalizarConsultaUseCase,
    ReabrirConsultaCerradaAutoUseCase,
    GetAgendaDiariaUseCase,
    GetFichaSaludPacienteUseCase,
    GetFichaSaludSocioUseCase,
    GetHistorialConsultasPacienteUseCase,
    GetHistorialMedicionesUseCase,
    GetHistorialTurnosPacienteUseCase,
    GetReporteEvolucionPacienteUseCase,
    GetResumenProgresoUseCase,
    GetTurnosDelDiaUseCase,
    GetTurnosRecepcionDiaUseCase,
    GetTurnoByIdUseCase,
    GetTurnoSocioByIdUseCase,
    GuardarMedicionesUseCase,
    GuardarObservacionesUseCase,
    IniciarConsultaUseCase,
    ListarHistorialFichaSaludNutricionistaUseCase,
    ListarHistorialFichaSaludSocioUseCase,
    ListMisTurnosUseCase,
    ListPacientesProfesionalUseCase,
    MarcarAusenteManualUseCase,
    NotificarSocioInasistenciaUseCase,
    ObtenerVersionFichaSaludNutricionistaUseCase,
    ObtenerVersionFichaSaludSocioUseCase,
    ReprogramarTurnoSocioUseCase,
    RegistrarAsistenciaTurnoUseCase,
    ReservarTurnoSocioUseCase,
    RevertirAusenteTurnoUseCase,
    RevertirCheckinTurnoUseCase,
    UpsertFichaSaludSocioUseCase,
    SlotComputationService,
    ValidacionesCreacionTurno,
    NotificacionesService,
  ],
  exports: [
    AbrirFichaDesdeTurnoUseCase,
    ActualizarMedicionUseCase,
    AsignarTurnoManualUseCase,
    AvisoLlegadaTardeUseCase,
    BloquearTurnoUseCase,
    CancelarTurnoSocioUseCase,
    CheckInTurnoUseCase,
    ConfirmarTurnoSocioUseCase,
    CrearTurnoEnNombreDeSocioUseCase,
    DesbloquearTurnoUseCase,
    EditarFichaPacienteNutricionistaUseCase,
    FinalizarConsultaPorInactividadUseCase,
    FinalizarConsultaUseCase,
    ReabrirConsultaCerradaAutoUseCase,
    GetAgendaDiariaUseCase,
    GetFichaSaludPacienteUseCase,
    GetFichaSaludSocioUseCase,
    GetHistorialConsultasPacienteUseCase,
    GetHistorialMedicionesUseCase,
    GetHistorialTurnosPacienteUseCase,
    GetReporteEvolucionPacienteUseCase,
    GetResumenProgresoUseCase,
    GetTurnosDelDiaUseCase,
    GetTurnosRecepcionDiaUseCase,
    GetTurnoByIdUseCase,
    GetTurnoSocioByIdUseCase,
    GuardarMedicionesUseCase,
    GuardarObservacionesUseCase,
    IniciarConsultaUseCase,
    ListarHistorialFichaSaludNutricionistaUseCase,
    ListarHistorialFichaSaludSocioUseCase,
    ListMisTurnosUseCase,
    ListPacientesProfesionalUseCase,
    MarcarAusenteManualUseCase,
    NotificarSocioInasistenciaUseCase,
    ObtenerVersionFichaSaludNutricionistaUseCase,
    ObtenerVersionFichaSaludSocioUseCase,
    ReprogramarTurnoSocioUseCase,
    RegistrarAsistenciaTurnoUseCase,
    ReservarTurnoSocioUseCase,
    RevertirAusenteTurnoUseCase,
    RevertirCheckinTurnoUseCase,
    UpsertFichaSaludSocioUseCase,
    SlotComputationService,
    ValidacionesCreacionTurno,
  ],
})
export class TurnosModule {}
