export * from './repositories.module';
export * from './agenda.repository';
export * from './socio.respository';
export * from './usuario.repository';
export * from './nutricionista.repository';
export * from './foto-progreso.repository';
export * from './objetivo.repository';
export * from './gimnasio.repository';
export * from './recepcionista.repository.impl';
