export interface SeedAlimentoEntry {
  nombre: string;
  cantidad: number;
  calorias: number;
  proteinas: number;
  carbohidratos: number;
  grasas: number;
  unidadMedida: string;
  grupoId: number;
  /** Azúcares (g) por porción */
  azucares?: number;
  /** Fibra alimentaria (g) por porción */
  fibraAlimentaria?: number;
  /** Grasas saturadas (g) por porción */
  grasasSaturadas?: number;
  /** Sodio (mg) por porción */
  sodio?: number;
}

/**
 * Catálogo masivo de alimentos argentinos con valores nutricionales
 * por 100 g / 100 ml / 1 unidad.
 * Fuentes: SARA 2 (ENNyS 2 - Ministerio de Salud), Argenfoods (UNLu),
 * etiquetado nutricional de productos reales.
 */
export const ALIMENTOS_CATALOG: SeedAlimentoEntry[] = [
  // ========== GRUPO 1: Lácteos, quesos y huevos ==========
  {
    nombre: 'Leche entera',
    cantidad: 100,
    calorias: 61,
    proteinas: 3,
    carbohidratos: 5,
    grasas: 3,
    unidadMedida: 'mililitro',
    grupoId: 1,
  },
  {
    nombre: 'Leche descremada',
    cantidad: 100,
    calorias: 35,
    proteinas: 3.4,
    carbohidratos: 5,
    grasas: 0.1,
    unidadMedida: 'mililitro',
    grupoId: 1,
  },
  {
    nombre: 'Leche semidescremada',
    cantidad: 100,
    calorias: 48,
    proteinas: 3.2,
    carbohidratos: 5,
    grasas: 1.5,
    unidadMedida: 'mililitro',
    grupoId: 1,
  },
  {
    nombre: 'Leche de cabra',
    cantidad: 100,
    calorias: 68,
    proteinas: 3.6,
    carbohidratos: 4.5,
    grasas: 4.1,
    unidadMedida: 'mililitro',
    grupoId: 1,
  },
  {
    nombre: 'Leche chocolatada (La Serenísima)',
    cantidad: 100,
    calorias: 83,
    proteinas: 3,
    carbohidratos: 12,
    grasas: 2.5,
    unidadMedida: 'mililitro',
    grupoId: 1,
  },
  {
    nombre: 'Yogur natural entero',
    cantidad: 100,
    calorias: 63,
    proteinas: 4,
    carbohidratos: 5,
    grasas: 3,
    unidadMedida: 'gramo',
    grupoId: 1,
  },
  {
    nombre: 'Yogur descremado',
    cantidad: 100,
    calorias: 43,
    proteinas: 4.5,
    carbohidratos: 6,
    grasas: 0.2,
    unidadMedida: 'gramo',
    grupoId: 1,
  },
  {
    nombre: 'Yogur griego',
    cantidad: 100,
    calorias: 97,
    proteinas: 9,
    carbohidratos: 4,
    grasas: 5,
    unidadMedida: 'gramo',
    grupoId: 1,
  },
  {
    nombre: 'Yogur bebible frutal',
    cantidad: 100,
    calorias: 75,
    proteinas: 2.5,
    carbohidratos: 13,
    grasas: 1.5,
    unidadMedida: 'mililitro',
    grupoId: 1,
  },
  {
    nombre: 'Queso crema (untable)',
    cantidad: 100,
    calorias: 250,
    proteinas: 6,
    carbohidratos: 3,
    grasas: 24,
    unidadMedida: 'gramo',
    grupoId: 1,
  },
  {
    nombre: 'Ricota',
    cantidad: 100,
    calorias: 150,
    proteinas: 10,
    carbohidratos: 4,
    grasas: 10,
    unidadMedida: 'gramo',
    grupoId: 1,
  },
  {
    nombre: 'Queso mozzarella',
    cantidad: 100,
    calorias: 280,
    proteinas: 25,
    carbohidratos: 2,
    grasas: 20,
    unidadMedida: 'gramo',
    grupoId: 1,
  },
  {
    nombre: 'Queso cremoso',
    cantidad: 100,
    calorias: 320,
    proteinas: 24,
    carbohidratos: 1.5,
    grasas: 25,
    unidadMedida: 'gramo',
    grupoId: 1,
  },
  {
    nombre: 'Queso parmesano',
    cantidad: 100,
    calorias: 420,
    proteinas: 35,
    carbohidratos: 3,
    grasas: 30,
    unidadMedida: 'gramo',
    grupoId: 1,
  },
  {
    nombre: 'Queso sardo',
    cantidad: 100,
    calorias: 360,
    proteinas: 28,
    carbohidratos: 2,
    grasas: 27,
    unidadMedida: 'gramo',
    grupoId: 1,
  },
  {
    nombre: 'Queso provolone',
    cantidad: 100,
    calorias: 350,
    proteinas: 26,
    carbohidratos: 1,
    grasas: 27,
    unidadMedida: 'gramo',
    grupoId: 1,
  },
  {
    nombre: 'Queso fontina',
    cantidad: 100,
    calorias: 340,
    proteinas: 25,
    carbohidratos: 1,
    grasas: 26,
    unidadMedida: 'gramo',
    grupoId: 1,
  },
  {
    nombre: 'Queso roquefort / azul',
    cantidad: 100,
    calorias: 350,
    proteinas: 20,
    carbohidratos: 2,
    grasas: 29,
    unidadMedida: 'gramo',
    grupoId: 1,
  },
  {
    nombre: 'Queso port salut',
    cantidad: 100,
    calorias: 300,
    proteinas: 22,
    carbohidratos: 2,
    grasas: 23,
    unidadMedida: 'gramo',
    grupoId: 1,
  },
  {
    nombre: 'Queso cuartirolo',
    cantidad: 100,
    calorias: 270,
    proteinas: 20,
    carbohidratos: 3,
    grasas: 20,
    unidadMedida: 'gramo',
    grupoId: 1,
  },
  {
    nombre: 'Queso de máquina (feteado)',
    cantidad: 100,
    calorias: 290,
    proteinas: 22,
    carbohidratos: 2,
    grasas: 22,
    unidadMedida: 'gramo',
    grupoId: 1,
  },
  {
    nombre: 'Manteca',
    cantidad: 100,
    calorias: 717,
    proteinas: 0.9,
    carbohidratos: 0.1,
    grasas: 81,
    unidadMedida: 'gramo',
    grupoId: 1,
  },
  {
    nombre: 'Crema de leche (crema doble)',
    cantidad: 100,
    calorias: 340,
    proteinas: 2.5,
    carbohidratos: 3,
    grasas: 35,
    unidadMedida: 'mililitro',
    grupoId: 1,
  },
  {
    nombre: 'Leche condensada',
    cantidad: 100,
    calorias: 320,
    proteinas: 8,
    carbohidratos: 55,
    grasas: 8,
    unidadMedida: 'mililitro',
    grupoId: 1,
  },
  {
    nombre: 'Huevo de gallina',
    cantidad: 1,
    calorias: 78,
    proteinas: 6.5,
    carbohidratos: 0.6,
    grasas: 5,
    unidadMedida: 'unidad',
    grupoId: 1,
  },
  {
    nombre: 'Clara de huevo',
    cantidad: 1,
    calorias: 17,
    proteinas: 3.6,
    carbohidratos: 0.2,
    grasas: 0,
    unidadMedida: 'unidad',
    grupoId: 1,
  },
  {
    nombre: 'Yema de huevo',
    cantidad: 1,
    calorias: 55,
    proteinas: 2.7,
    carbohidratos: 0.6,
    grasas: 4.5,
    unidadMedida: 'unidad',
    grupoId: 1,
  },
  {
    nombre: 'Huevo de codorniz',
    cantidad: 1,
    calorias: 14,
    proteinas: 1.2,
    carbohidratos: 0.04,
    grasas: 1,
    unidadMedida: 'unidad',
    grupoId: 1,
  },
  {
    nombre: 'Dulce de leche (La Serenísima)',
    cantidad: 100,
    calorias: 315,
    proteinas: 6,
    carbohidratos: 58,
    grasas: 7,
    unidadMedida: 'gramo',
    grupoId: 1,
  },
  {
    nombre: 'Leche en polvo entera',
    cantidad: 100,
    calorias: 500,
    proteinas: 26,
    carbohidratos: 38,
    grasas: 27,
    unidadMedida: 'gramo',
    grupoId: 1,
  },

  // ========== GRUPO 2: Hierbas, condimentos y especias ==========
  {
    nombre: 'Ajo crudo',
    cantidad: 100,
    calorias: 149,
    proteinas: 6.4,
    carbohidratos: 33,
    grasas: 0.5,
    unidadMedida: 'gramo',
    grupoId: 2,
  },
  {
    nombre: 'Perejil fresco',
    cantidad: 100,
    calorias: 36,
    proteinas: 3,
    carbohidratos: 6,
    grasas: 0.8,
    unidadMedida: 'gramo',
    grupoId: 2,
  },
  {
    nombre: 'Orégano seco',
    cantidad: 100,
    calorias: 265,
    proteinas: 9,
    carbohidratos: 69,
    grasas: 4.3,
    unidadMedida: 'gramo',
    grupoId: 2,
  },
  {
    nombre: 'Albahaca fresca',
    cantidad: 100,
    calorias: 23,
    proteinas: 3.2,
    carbohidratos: 2.7,
    grasas: 0.6,
    unidadMedida: 'gramo',
    grupoId: 2,
  },
  {
    nombre: 'Romero seco',
    cantidad: 100,
    calorias: 335,
    proteinas: 4.9,
    carbohidratos: 64,
    grasas: 15,
    unidadMedida: 'gramo',
    grupoId: 2,
  },
  {
    nombre: 'Tomillo seco',
    cantidad: 100,
    calorias: 275,
    proteinas: 9.1,
    carbohidratos: 64,
    grasas: 7.4,
    unidadMedida: 'gramo',
    grupoId: 2,
  },
  {
    nombre: 'Laurel seco',
    cantidad: 100,
    calorias: 315,
    proteinas: 7.4,
    carbohidratos: 75,
    grasas: 8.4,
    unidadMedida: 'gramo',
    grupoId: 2,
  },
  {
    nombre: 'Salvia seca',
    cantidad: 100,
    calorias: 315,
    proteinas: 10.6,
    carbohidratos: 61,
    grasas: 12.8,
    unidadMedida: 'gramo',
    grupoId: 2,
  },
  {
    nombre: 'Comino en grano',
    cantidad: 100,
    calorias: 375,
    proteinas: 17.8,
    carbohidratos: 44,
    grasas: 22.3,
    unidadMedida: 'gramo',
    grupoId: 2,
  },
  {
    nombre: 'Pimentón dulce',
    cantidad: 100,
    calorias: 280,
    proteinas: 14.1,
    carbohidratos: 54,
    grasas: 12.9,
    unidadMedida: 'gramo',
    grupoId: 2,
  },
  {
    nombre: 'Curry en polvo',
    cantidad: 100,
    calorias: 325,
    proteinas: 14,
    carbohidratos: 55,
    grasas: 14,
    unidadMedida: 'gramo',
    grupoId: 2,
  },
  {
    nombre: 'Cúrcuma en polvo',
    cantidad: 100,
    calorias: 310,
    proteinas: 9.7,
    carbohidratos: 65,
    grasas: 3.3,
    unidadMedida: 'gramo',
    grupoId: 2,
  },
  {
    nombre: 'Jengibre fresco',
    cantidad: 100,
    calorias: 80,
    proteinas: 1.8,
    carbohidratos: 18,
    grasas: 0.8,
    unidadMedida: 'gramo',
    grupoId: 2,
  },
  {
    nombre: 'Canela en polvo',
    cantidad: 100,
    calorias: 250,
    proteinas: 4,
    carbohidratos: 80,
    grasas: 1.2,
    unidadMedida: 'gramo',
    grupoId: 2,
  },
  {
    nombre: 'Clavo de olor',
    cantidad: 100,
    calorias: 275,
    proteinas: 6,
    carbohidratos: 66,
    grasas: 13,
    unidadMedida: 'gramo',
    grupoId: 2,
  },
  {
    nombre: 'Nuez moscada',
    cantidad: 100,
    calorias: 525,
    proteinas: 5.8,
    carbohidratos: 49,
    grasas: 36,
    unidadMedida: 'gramo',
    grupoId: 2,
  },
  {
    nombre: 'Mostaza preparada',
    cantidad: 100,
    calorias: 67,
    proteinas: 3.7,
    carbohidratos: 6,
    grasas: 3.7,
    unidadMedida: 'gramo',
    grupoId: 2,
  },
  {
    nombre: 'Vinagre de alcohol',
    cantidad: 100,
    calorias: 18,
    proteinas: 0,
    carbohidratos: 0.5,
    grasas: 0,
    unidadMedida: 'mililitro',
    grupoId: 2,
  },
  {
    nombre: 'Vinagre de manzana',
    cantidad: 100,
    calorias: 21,
    proteinas: 0,
    carbohidratos: 1,
    grasas: 0,
    unidadMedida: 'mililitro',
    grupoId: 2,
  },
  {
    nombre: 'Sal fina (entabla)',
    cantidad: 100,
    calorias: 0,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 0,
    unidadMedida: 'gramo',
    grupoId: 2,
  },
  {
    nombre: 'Pimienta negra molida',
    cantidad: 100,
    calorias: 255,
    proteinas: 10.4,
    carbohidratos: 64,
    grasas: 3.3,
    unidadMedida: 'gramo',
    grupoId: 2,
  },

  // ========== GRUPO 3: Alimentos infantiles y fórmulas ==========
  {
    nombre: 'Fórmula infantil en polvo (etapa 1)',
    cantidad: 100,
    calorias: 510,
    proteinas: 10,
    carbohidratos: 57,
    grasas: 27,
    unidadMedida: 'gramo',
    grupoId: 3,
  },
  {
    nombre: 'Fórmula infantil en polvo (etapa 2)',
    cantidad: 100,
    calorias: 500,
    proteinas: 12,
    carbohidratos: 55,
    grasas: 26,
    unidadMedida: 'gramo',
    grupoId: 3,
  },
  {
    nombre: 'Papilla de frutas (Nestlé)',
    cantidad: 100,
    calorias: 80,
    proteinas: 0.5,
    carbohidratos: 18,
    grasas: 0.3,
    unidadMedida: 'gramo',
    grupoId: 3,
  },
  {
    nombre: 'Papilla de verduras y pollo (Nestlé)',
    cantidad: 100,
    calorias: 65,
    proteinas: 3,
    carbohidratos: 8,
    grasas: 2,
    unidadMedida: 'gramo',
    grupoId: 3,
  },
  {
    nombre: 'Cereal infantil fortificado (Nestlé)',
    cantidad: 100,
    calorias: 380,
    proteinas: 7,
    carbohidratos: 80,
    grasas: 3,
    unidadMedida: 'gramo',
    grupoId: 3,
  },

  // ========== GRUPO 4: Aceites, grasas y aderezos ==========
  {
    nombre: 'Aceite de oliva extra virgen',
    cantidad: 100,
    calorias: 884,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 100,
    unidadMedida: 'mililitro',
    grupoId: 4,
  },
  {
    nombre: 'Aceite de girasol (Natura)',
    cantidad: 100,
    calorias: 884,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 100,
    unidadMedida: 'mililitro',
    grupoId: 4,
  },
  {
    nombre: 'Aceite de maíz',
    cantidad: 100,
    calorias: 884,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 100,
    unidadMedida: 'mililitro',
    grupoId: 4,
  },
  {
    nombre: 'Aceite de canola',
    cantidad: 100,
    calorias: 884,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 100,
    unidadMedida: 'mililitro',
    grupoId: 4,
  },
  {
    nombre: 'Aceite de coco',
    cantidad: 100,
    calorias: 862,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 100,
    unidadMedida: 'mililitro',
    grupoId: 4,
  },
  {
    nombre: 'Aceite de sésamo',
    cantidad: 100,
    calorias: 884,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 100,
    unidadMedida: 'mililitro',
    grupoId: 4,
  },
  {
    nombre: 'Mayonesa (Hellmanns / Natura)',
    cantidad: 100,
    calorias: 720,
    proteinas: 1,
    carbohidratos: 1,
    grasas: 78,
    unidadMedida: 'gramo',
    grupoId: 4,
  },
  {
    nombre: 'Mayonesa light (Hellmanns)',
    cantidad: 100,
    calorias: 350,
    proteinas: 0.5,
    carbohidratos: 2,
    grasas: 37,
    unidadMedida: 'gramo',
    grupoId: 4,
  },
  {
    nombre: 'Ketchup (Hellmanns / La Campagnola)',
    cantidad: 100,
    calorias: 110,
    proteinas: 1,
    carbohidratos: 25,
    grasas: 0.2,
    unidadMedida: 'gramo',
    grupoId: 4,
  },
  {
    nombre: 'Mostaza (Savora)',
    cantidad: 100,
    calorias: 120,
    proteinas: 5,
    carbohidratos: 8,
    grasas: 7,
    unidadMedida: 'gramo',
    grupoId: 4,
  },
  {
    nombre: 'Salsa golf (Hellmanns)',
    cantidad: 100,
    calorias: 450,
    proteinas: 0.5,
    carbohidratos: 5,
    grasas: 48,
    unidadMedida: 'gramo',
    grupoId: 4,
  },
  {
    nombre: 'Vinagreta clásica',
    cantidad: 100,
    calorias: 400,
    proteinas: 0.2,
    carbohidratos: 2,
    grasas: 44,
    unidadMedida: 'mililitro',
    grupoId: 4,
  },
  {
    nombre: 'Grasa vacuna refinada',
    cantidad: 100,
    calorias: 900,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 100,
    unidadMedida: 'gramo',
    grupoId: 4,
  },
  {
    nombre: 'Rocío vegetal en aerosol (Lira)',
    cantidad: 100,
    calorias: 830,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 92,
    unidadMedida: 'mililitro',
    grupoId: 4,
  },

  // ========== GRUPO 5: Pollo y carnes de ave ==========
  {
    nombre: 'Pechuga de pollo sin piel',
    cantidad: 100,
    calorias: 165,
    proteinas: 31,
    carbohidratos: 0,
    grasas: 4,
    unidadMedida: 'gramo',
    grupoId: 5,
  },
  {
    nombre: 'Muslo de pollo sin piel',
    cantidad: 100,
    calorias: 180,
    proteinas: 26,
    carbohidratos: 0,
    grasas: 8,
    unidadMedida: 'gramo',
    grupoId: 5,
  },
  {
    nombre: 'Pata muslo de pollo',
    cantidad: 100,
    calorias: 200,
    proteinas: 24,
    carbohidratos: 0,
    grasas: 11,
    unidadMedida: 'gramo',
    grupoId: 5,
  },
  {
    nombre: 'Ala de pollo',
    cantidad: 100,
    calorias: 220,
    proteinas: 22,
    carbohidratos: 0,
    grasas: 14,
    unidadMedida: 'gramo',
    grupoId: 5,
  },
  {
    nombre: 'Hígado de pollo',
    cantidad: 100,
    calorias: 135,
    proteinas: 20,
    carbohidratos: 2,
    grasas: 5,
    unidadMedida: 'gramo',
    grupoId: 5,
  },
  {
    nombre: 'Pollo entero sin menudos',
    cantidad: 100,
    calorias: 190,
    proteinas: 26,
    carbohidratos: 0,
    grasas: 9,
    unidadMedida: 'gramo',
    grupoId: 5,
  },
  {
    nombre: 'Pechuga de pavo',
    cantidad: 100,
    calorias: 135,
    proteinas: 30,
    carbohidratos: 0,
    grasas: 1,
    unidadMedida: 'gramo',
    grupoId: 5,
  },
  {
    nombre: 'Jamón de pavo (feteado)',
    cantidad: 100,
    calorias: 120,
    proteinas: 18,
    carbohidratos: 2,
    grasas: 4,
    unidadMedida: 'gramo',
    grupoId: 5,
  },
  {
    nombre: 'Carne de pato sin piel',
    cantidad: 100,
    calorias: 200,
    proteinas: 24,
    carbohidratos: 0,
    grasas: 11,
    unidadMedida: 'gramo',
    grupoId: 5,
  },
  {
    nombre: 'Carne de codorniz',
    cantidad: 100,
    calorias: 190,
    proteinas: 22,
    carbohidratos: 0,
    grasas: 11,
    unidadMedida: 'gramo',
    grupoId: 5,
  },
  {
    nombre: 'Milanesa de pollo (congelada, cocida)',
    cantidad: 100,
    calorias: 280,
    proteinas: 18,
    carbohidratos: 18,
    grasas: 15,
    unidadMedida: 'gramo',
    grupoId: 5,
  },
  {
    nombre: 'Suprema de pollo rebozada (cocida)',
    cantidad: 100,
    calorias: 260,
    proteinas: 20,
    carbohidratos: 15,
    grasas: 13,
    unidadMedida: 'gramo',
    grupoId: 5,
  },

  // ========== GRUPO 6: Sopas, salsas y caldos ==========
  {
    nombre: 'Caldo de verduras (casero)',
    cantidad: 100,
    calorias: 5,
    proteinas: 0.3,
    carbohidratos: 1,
    grasas: 0.1,
    unidadMedida: 'mililitro',
    grupoId: 6,
  },
  {
    nombre: 'Caldo de pollo (casero)',
    cantidad: 100,
    calorias: 8,
    proteinas: 1,
    carbohidratos: 0.5,
    grasas: 0.3,
    unidadMedida: 'mililitro',
    grupoId: 6,
  },
  {
    nombre: 'Caldo de carne (casero)',
    cantidad: 100,
    calorias: 10,
    proteinas: 1.2,
    carbohidratos: 0.4,
    grasas: 0.4,
    unidadMedida: 'mililitro',
    grupoId: 6,
  },
  {
    nombre: 'Caldo concentrado (Maggi)',
    cantidad: 100,
    calorias: 180,
    proteinas: 15,
    carbohidratos: 20,
    grasas: 4,
    unidadMedida: 'gramo',
    grupoId: 6,
  },
  {
    nombre: 'Sopa crema de zapallo (Knorr)',
    cantidad: 100,
    calorias: 40,
    proteinas: 1,
    carbohidratos: 6,
    grasas: 1.5,
    unidadMedida: 'mililitro',
    grupoId: 6,
  },
  {
    nombre: 'Sopa crema de choclo (Knorr)',
    cantidad: 100,
    calorias: 45,
    proteinas: 1.2,
    carbohidratos: 7,
    grasas: 1.5,
    unidadMedida: 'mililitro',
    grupoId: 6,
  },
  {
    nombre: 'Salsa de tomate (La Campagnola)',
    cantidad: 100,
    calorias: 35,
    proteinas: 1.5,
    carbohidratos: 6,
    grasas: 0.5,
    unidadMedida: 'gramo',
    grupoId: 6,
  },
  {
    nombre: 'Salsa blanca (casera)',
    cantidad: 100,
    calorias: 120,
    proteinas: 3,
    carbohidratos: 9,
    grasas: 8,
    unidadMedida: 'gramo',
    grupoId: 6,
  },
  {
    nombre: 'Salsa barbacoa',
    cantidad: 100,
    calorias: 160,
    proteinas: 1,
    carbohidratos: 30,
    grasas: 4,
    unidadMedida: 'gramo',
    grupoId: 6,
  },
  {
    nombre: 'Puré de tomate (La Campagnola)',
    cantidad: 100,
    calorias: 32,
    proteinas: 1.5,
    carbohidratos: 6,
    grasas: 0.3,
    unidadMedida: 'gramo',
    grupoId: 6,
  },
  {
    nombre: 'Salsa criolla (casera)',
    cantidad: 100,
    calorias: 55,
    proteinas: 1,
    carbohidratos: 6,
    grasas: 3,
    unidadMedida: 'gramo',
    grupoId: 6,
  },
  {
    nombre: 'Salsa filetto (casera)',
    cantidad: 100,
    calorias: 50,
    proteinas: 1.5,
    carbohidratos: 7,
    grasas: 1.5,
    unidadMedida: 'gramo',
    grupoId: 6,
  },

  // ========== GRUPO 7: Fiambres y embutidos ==========
  {
    nombre: 'Jamón cocido (feteado)',
    cantidad: 100,
    calorias: 145,
    proteinas: 20,
    carbohidratos: 2,
    grasas: 6,
    unidadMedida: 'gramo',
    grupoId: 7,
  },
  {
    nombre: 'Jamón crudo',
    cantidad: 100,
    calorias: 200,
    proteinas: 26,
    carbohidratos: 0.5,
    grasas: 10,
    unidadMedida: 'gramo',
    grupoId: 7,
  },
  {
    nombre: 'Salame (tipo Milán)',
    cantidad: 100,
    calorias: 380,
    proteinas: 25,
    carbohidratos: 1,
    grasas: 30,
    unidadMedida: 'gramo',
    grupoId: 7,
  },
  {
    nombre: 'Salame (tipo Socola)',
    cantidad: 100,
    calorias: 400,
    proteinas: 22,
    carbohidratos: 0.5,
    grasas: 35,
    unidadMedida: 'gramo',
    grupoId: 7,
  },
  {
    nombre: 'Longaniza',
    cantidad: 100,
    calorias: 320,
    proteinas: 20,
    carbohidratos: 1,
    grasas: 26,
    unidadMedida: 'gramo',
    grupoId: 7,
  },
  {
    nombre: 'Chorizo parrillero',
    cantidad: 100,
    calorias: 330,
    proteinas: 18,
    carbohidratos: 2,
    grasas: 28,
    unidadMedida: 'gramo',
    grupoId: 7,
  },
  {
    nombre: 'Morcilla',
    cantidad: 100,
    calorias: 280,
    proteinas: 15,
    carbohidratos: 8,
    grasas: 21,
    unidadMedida: 'gramo',
    grupoId: 7,
  },
  {
    nombre: 'Panceta ahumada (tocino)',
    cantidad: 100,
    calorias: 540,
    proteinas: 12,
    carbohidratos: 0.5,
    grasas: 56,
    unidadMedida: 'gramo',
    grupoId: 7,
  },
  {
    nombre: 'Bondiola',
    cantidad: 100,
    calorias: 260,
    proteinas: 22,
    carbohidratos: 1,
    grasas: 18,
    unidadMedida: 'gramo',
    grupoId: 7,
  },
  {
    nombre: 'Salchichón',
    cantidad: 100,
    calorias: 360,
    proteinas: 22,
    carbohidratos: 1,
    grasas: 29,
    unidadMedida: 'gramo',
    grupoId: 7,
  },
  {
    nombre: 'Mortadela',
    cantidad: 100,
    calorias: 280,
    proteinas: 15,
    carbohidratos: 3,
    grasas: 23,
    unidadMedida: 'gramo',
    grupoId: 7,
  },
  {
    nombre: 'Pastrón (carne curada)',
    cantidad: 100,
    calorias: 200,
    proteinas: 25,
    carbohidratos: 1,
    grasas: 10,
    unidadMedida: 'gramo',
    grupoId: 7,
  },

  // ========== GRUPO 8: Cereales de desayuno y barras ==========
  {
    nombre: "Corn flakes (Kellogg's)",
    cantidad: 100,
    calorias: 360,
    proteinas: 7,
    carbohidratos: 84,
    grasas: 0.4,
    unidadMedida: 'gramo',
    grupoId: 8,
  },
  {
    nombre: 'Granola artesanal',
    cantidad: 100,
    calorias: 450,
    proteinas: 10,
    carbohidratos: 60,
    grasas: 18,
    unidadMedida: 'gramo',
    grupoId: 8,
  },
  {
    nombre: 'Avena instantánea (Granix)',
    cantidad: 100,
    calorias: 375,
    proteinas: 14,
    carbohidratos: 62,
    grasas: 7,
    unidadMedida: 'gramo',
    grupoId: 8,
  },
  {
    nombre: 'Cereal integral (Granix Vital)',
    cantidad: 100,
    calorias: 350,
    proteinas: 10,
    carbohidratos: 72,
    grasas: 3,
    unidadMedida: 'gramo',
    grupoId: 8,
  },
  {
    nombre: "Zucaritas (Kellogg's)",
    cantidad: 100,
    calorias: 380,
    proteinas: 5,
    carbohidratos: 88,
    grasas: 1.5,
    unidadMedida: 'gramo',
    grupoId: 8,
  },
  {
    nombre: "Froot Loops (Kellogg's)",
    cantidad: 100,
    calorias: 375,
    proteinas: 5,
    carbohidratos: 86,
    grasas: 2.5,
    unidadMedida: 'gramo',
    grupoId: 8,
  },
  {
    nombre: 'Barra de cereal frutal (Granix)',
    cantidad: 1,
    calorias: 120,
    proteinas: 2,
    carbohidratos: 20,
    grasas: 3.5,
    unidadMedida: 'unidad',
    grupoId: 8,
  },
  {
    nombre: 'Barra de cereal con chocolate (Granix)',
    cantidad: 1,
    calorias: 135,
    proteinas: 2.5,
    carbohidratos: 21,
    grasas: 5,
    unidadMedida: 'unidad',
    grupoId: 8,
  },
  {
    nombre: 'Barra proteica (MaxSport)',
    cantidad: 1,
    calorias: 180,
    proteinas: 15,
    carbohidratos: 18,
    grasas: 6,
    unidadMedida: 'unidad',
    grupoId: 8,
  },

  // ========== GRUPO 9: Frutas y jugos naturales ==========
  {
    nombre: 'Manzana (Red Delicious)',
    cantidad: 1,
    calorias: 95,
    proteinas: 0.5,
    carbohidratos: 25,
    grasas: 0.3,
    unidadMedida: 'unidad',
    grupoId: 9,
  },
  {
    nombre: 'Manzana verde (Granny Smith)',
    cantidad: 1,
    calorias: 85,
    proteinas: 0.4,
    carbohidratos: 22,
    grasas: 0.2,
    unidadMedida: 'unidad',
    grupoId: 9,
  },
  {
    nombre: 'Banana (Cavendish)',
    cantidad: 1,
    calorias: 105,
    proteinas: 1.3,
    carbohidratos: 27,
    grasas: 0.4,
    unidadMedida: 'unidad',
    grupoId: 9,
  },
  {
    nombre: 'Naranja (Valencia)',
    cantidad: 1,
    calorias: 62,
    proteinas: 1.2,
    carbohidratos: 15,
    grasas: 0.2,
    unidadMedida: 'unidad',
    grupoId: 9,
  },
  {
    nombre: 'Mandarina (Ellendale)',
    cantidad: 1,
    calorias: 50,
    proteinas: 0.8,
    carbohidratos: 13,
    grasas: 0.1,
    unidadMedida: 'unidad',
    grupoId: 9,
  },
  {
    nombre: 'Limón',
    cantidad: 1,
    calorias: 17,
    proteinas: 0.6,
    carbohidratos: 5,
    grasas: 0.1,
    unidadMedida: 'unidad',
    grupoId: 9,
  },
  {
    nombre: 'Pomelo (rosado)',
    cantidad: 1,
    calorias: 52,
    proteinas: 1,
    carbohidratos: 13,
    grasas: 0.1,
    unidadMedida: 'unidad',
    grupoId: 9,
  },
  {
    nombre: 'Durazno (tipo Red Globe)',
    cantidad: 1,
    calorias: 60,
    proteinas: 1,
    carbohidratos: 14,
    grasas: 0.4,
    unidadMedida: 'unidad',
    grupoId: 9,
  },
  {
    nombre: 'Pelón (durazno pelado en almíbar)',
    cantidad: 100,
    calorias: 75,
    proteinas: 0.5,
    carbohidratos: 19,
    grasas: 0.1,
    unidadMedida: 'gramo',
    grupoId: 9,
  },
  {
    nombre: 'Ciruela (tipo Santa Rosa)',
    cantidad: 1,
    calorias: 46,
    proteinas: 0.7,
    carbohidratos: 11,
    grasas: 0.3,
    unidadMedida: 'unidad',
    grupoId: 9,
  },
  {
    nombre: 'Damasco',
    cantidad: 1,
    calorias: 17,
    proteinas: 0.5,
    carbohidratos: 4,
    grasas: 0.1,
    unidadMedida: 'unidad',
    grupoId: 9,
  },
  {
    nombre: 'Cereza (picota)',
    cantidad: 100,
    calorias: 50,
    proteinas: 1,
    carbohidratos: 12,
    grasas: 0.3,
    unidadMedida: 'gramo',
    grupoId: 9,
  },
  {
    nombre: 'Frutilla (fresón)',
    cantidad: 100,
    calorias: 32,
    proteinas: 0.7,
    carbohidratos: 8,
    grasas: 0.3,
    unidadMedida: 'gramo',
    grupoId: 9,
  },
  {
    nombre: 'Frambuesa',
    cantidad: 100,
    calorias: 52,
    proteinas: 1.2,
    carbohidratos: 12,
    grasas: 0.7,
    unidadMedida: 'gramo',
    grupoId: 9,
  },
  {
    nombre: 'Arándano (blueberry)',
    cantidad: 100,
    calorias: 57,
    proteinas: 0.7,
    carbohidratos: 14,
    grasas: 0.3,
    unidadMedida: 'gramo',
    grupoId: 9,
  },
  {
    nombre: 'Uva (criolla / variedad Cereza)',
    cantidad: 100,
    calorias: 75,
    proteinas: 0.6,
    carbohidratos: 18,
    grasas: 0.2,
    unidadMedida: 'gramo',
    grupoId: 9,
  },
  {
    nombre: 'Sandía (tipo Crimson Sweet)',
    cantidad: 100,
    calorias: 30,
    proteinas: 0.6,
    carbohidratos: 8,
    grasas: 0.2,
    unidadMedida: 'gramo',
    grupoId: 9,
  },
  {
    nombre: 'Melón (tipo Rocío)',
    cantidad: 100,
    calorias: 34,
    proteinas: 0.8,
    carbohidratos: 8,
    grasas: 0.2,
    unidadMedida: 'gramo',
    grupoId: 9,
  },
  {
    nombre: 'Ananá (piña)',
    cantidad: 100,
    calorias: 50,
    proteinas: 0.5,
    carbohidratos: 13,
    grasas: 0.1,
    unidadMedida: 'gramo',
    grupoId: 9,
  },
  {
    nombre: 'Kiwi (Hayward)',
    cantidad: 1,
    calorias: 42,
    proteinas: 0.8,
    carbohidratos: 10,
    grasas: 0.4,
    unidadMedida: 'unidad',
    grupoId: 9,
  },
  {
    nombre: 'Mango (Tommy Atkins)',
    cantidad: 100,
    calorias: 60,
    proteinas: 0.8,
    carbohidratos: 15,
    grasas: 0.4,
    unidadMedida: 'gramo',
    grupoId: 9,
  },
  {
    nombre: 'Palta (Hass)',
    cantidad: 100,
    calorias: 160,
    proteinas: 2,
    carbohidratos: 2,
    grasas: 15,
    unidadMedida: 'gramo',
    grupoId: 9,
  },
  {
    nombre: 'Papaya (mamón)',
    cantidad: 100,
    calorias: 43,
    proteinas: 0.5,
    carbohidratos: 11,
    grasas: 0.2,
    unidadMedida: 'gramo',
    grupoId: 9,
  },
  {
    nombre: 'Higos frescos',
    cantidad: 1,
    calorias: 37,
    proteinas: 0.3,
    carbohidratos: 10,
    grasas: 0.1,
    unidadMedida: 'unidad',
    grupoId: 9,
  },
  {
    nombre: 'Coco fresco rallado',
    cantidad: 100,
    calorias: 354,
    proteinas: 3.3,
    carbohidratos: 15,
    grasas: 33,
    unidadMedida: 'gramo',
    grupoId: 9,
  },
  {
    nombre: 'Jugo de naranja natural exprimido',
    cantidad: 100,
    calorias: 45,
    proteinas: 0.7,
    carbohidratos: 10,
    grasas: 0.2,
    unidadMedida: 'mililitro',
    grupoId: 9,
  },
  {
    nombre: 'Jugo de limón natural',
    cantidad: 100,
    calorias: 22,
    proteinas: 0.4,
    carbohidratos: 7,
    grasas: 0.1,
    unidadMedida: 'mililitro',
    grupoId: 9,
  },
  {
    nombre: 'Jugo de pomelo natural',
    cantidad: 100,
    calorias: 39,
    proteinas: 0.5,
    carbohidratos: 9,
    grasas: 0.1,
    unidadMedida: 'mililitro',
    grupoId: 9,
  },

  // ========== GRUPO 10: Carne de cerdo y derivados ==========
  {
    nombre: 'Lomo de cerdo',
    cantidad: 100,
    calorias: 180,
    proteinas: 28,
    carbohidratos: 0,
    grasas: 7,
    unidadMedida: 'gramo',
    grupoId: 10,
  },
  {
    nombre: 'Costeleta de cerdo',
    cantidad: 100,
    calorias: 230,
    proteinas: 24,
    carbohidratos: 0,
    grasas: 14,
    unidadMedida: 'gramo',
    grupoId: 10,
  },
  {
    nombre: 'Carré de cerdo',
    cantidad: 100,
    calorias: 210,
    proteinas: 25,
    carbohidratos: 0,
    grasas: 12,
    unidadMedida: 'gramo',
    grupoId: 10,
  },
  {
    nombre: 'Pierna de cerdo',
    cantidad: 100,
    calorias: 200,
    proteinas: 27,
    carbohidratos: 0,
    grasas: 10,
    unidadMedida: 'gramo',
    grupoId: 10,
  },
  {
    nombre: 'Peceto de cerdo',
    cantidad: 100,
    calorias: 170,
    proteinas: 26,
    carbohidratos: 0,
    grasas: 7,
    unidadMedida: 'gramo',
    grupoId: 10,
  },
  {
    nombre: 'Matambre de cerdo',
    cantidad: 100,
    calorias: 220,
    proteinas: 22,
    carbohidratos: 0,
    grasas: 14,
    unidadMedida: 'gramo',
    grupoId: 10,
  },
  {
    nombre: 'Osobuco de cerdo',
    cantidad: 100,
    calorias: 190,
    proteinas: 24,
    carbohidratos: 0,
    grasas: 10,
    unidadMedida: 'gramo',
    grupoId: 10,
  },
  {
    nombre: 'Pechito de cerdo (costillar)',
    cantidad: 100,
    calorias: 290,
    proteinas: 18,
    carbohidratos: 0,
    grasas: 24,
    unidadMedida: 'gramo',
    grupoId: 10,
  },
  {
    nombre: 'Carne de cerdo picada',
    cantidad: 100,
    calorias: 250,
    proteinas: 22,
    carbohidratos: 0,
    grasas: 18,
    unidadMedida: 'gramo',
    grupoId: 10,
  },
  {
    nombre: 'Chorizo de cerdo',
    cantidad: 100,
    calorias: 340,
    proteinas: 17,
    carbohidratos: 2,
    grasas: 29,
    unidadMedida: 'gramo',
    grupoId: 10,
  },

  // ========== GRUPO 11: Verduras, hortalizas y tubérculos ==========
  {
    nombre: 'Papa blanca cocida',
    cantidad: 100,
    calorias: 77,
    proteinas: 2,
    carbohidratos: 17,
    grasas: 0,
    unidadMedida: 'gramo',
    grupoId: 11,
  },
  {
    nombre: 'Papa lavada (cruda)',
    cantidad: 100,
    calorias: 80,
    proteinas: 2.1,
    carbohidratos: 18,
    grasas: 0.1,
    unidadMedida: 'gramo',
    grupoId: 11,
  },
  {
    nombre: 'Batata (camote) cruda',
    cantidad: 100,
    calorias: 86,
    proteinas: 1.6,
    carbohidratos: 20,
    grasas: 0.1,
    unidadMedida: 'gramo',
    grupoId: 11,
  },
  {
    nombre: 'Mandioca (casava) cruda',
    cantidad: 100,
    calorias: 120,
    proteinas: 1.2,
    carbohidratos: 28,
    grasas: 0.2,
    unidadMedida: 'gramo',
    grupoId: 11,
  },
  {
    nombre: 'Zanahoria cruda',
    cantidad: 100,
    calorias: 41,
    proteinas: 1,
    carbohidratos: 10,
    grasas: 0,
    unidadMedida: 'gramo',
    grupoId: 11,
  },
  {
    nombre: 'Cebolla cruda',
    cantidad: 100,
    calorias: 40,
    proteinas: 1.1,
    carbohidratos: 9,
    grasas: 0.1,
    unidadMedida: 'gramo',
    grupoId: 11,
  },
  {
    nombre: 'Cebolla de verdeo',
    cantidad: 100,
    calorias: 32,
    proteinas: 1.8,
    carbohidratos: 7,
    grasas: 0.2,
    unidadMedida: 'gramo',
    grupoId: 11,
  },
  {
    nombre: 'Puerro',
    cantidad: 100,
    calorias: 30,
    proteinas: 1.3,
    carbohidratos: 6,
    grasas: 0.2,
    unidadMedida: 'gramo',
    grupoId: 11,
  },
  {
    nombre: 'Lechuga (criolla)',
    cantidad: 100,
    calorias: 15,
    proteinas: 1.4,
    carbohidratos: 3,
    grasas: 0.2,
    unidadMedida: 'gramo',
    grupoId: 11,
  },
  {
    nombre: 'Lechuga (mantecosa)',
    cantidad: 100,
    calorias: 13,
    proteinas: 1.5,
    carbohidratos: 2,
    grasas: 0.2,
    unidadMedida: 'gramo',
    grupoId: 11,
  },
  {
    nombre: 'Espinaca cruda',
    cantidad: 100,
    calorias: 23,
    proteinas: 2.9,
    carbohidratos: 4,
    grasas: 0.4,
    unidadMedida: 'gramo',
    grupoId: 11,
  },
  {
    nombre: 'Acelga cruda',
    cantidad: 100,
    calorias: 19,
    proteinas: 1.8,
    carbohidratos: 4,
    grasas: 0.2,
    unidadMedida: 'gramo',
    grupoId: 11,
  },
  {
    nombre: 'Rúcula',
    cantidad: 100,
    calorias: 25,
    proteinas: 2.6,
    carbohidratos: 4,
    grasas: 0.7,
    unidadMedida: 'gramo',
    grupoId: 11,
  },
  {
    nombre: 'Brócoli crudo',
    cantidad: 100,
    calorias: 34,
    proteinas: 2.8,
    carbohidratos: 7,
    grasas: 0.4,
    unidadMedida: 'gramo',
    grupoId: 11,
  },
  {
    nombre: 'Coliflor cruda',
    cantidad: 100,
    calorias: 25,
    proteinas: 1.9,
    carbohidratos: 5,
    grasas: 0.3,
    unidadMedida: 'gramo',
    grupoId: 11,
  },
  {
    nombre: 'Repollo blanco crudo',
    cantidad: 100,
    calorias: 25,
    proteinas: 1.3,
    carbohidratos: 6,
    grasas: 0.1,
    unidadMedida: 'gramo',
    grupoId: 11,
  },
  {
    nombre: 'Coles de Bruselas',
    cantidad: 100,
    calorias: 43,
    proteinas: 3.4,
    carbohidratos: 9,
    grasas: 0.3,
    unidadMedida: 'gramo',
    grupoId: 11,
  },
  {
    nombre: 'Tomate redondo crudo',
    cantidad: 100,
    calorias: 18,
    proteinas: 0.9,
    carbohidratos: 4,
    grasas: 0.2,
    unidadMedida: 'gramo',
    grupoId: 11,
  },
  {
    nombre: 'Tomate perita (enlatado)',
    cantidad: 100,
    calorias: 20,
    proteinas: 1,
    carbohidratos: 4,
    grasas: 0.2,
    unidadMedida: 'gramo',
    grupoId: 11,
  },
  {
    nombre: 'Morrón rojo crudo',
    cantidad: 100,
    calorias: 31,
    proteinas: 1,
    carbohidratos: 6,
    grasas: 0.3,
    unidadMedida: 'gramo',
    grupoId: 11,
  },
  {
    nombre: 'Morrón verde crudo',
    cantidad: 100,
    calorias: 20,
    proteinas: 0.9,
    carbohidratos: 5,
    grasas: 0.2,
    unidadMedida: 'gramo',
    grupoId: 11,
  },
  {
    nombre: 'Zapallito (zucchini) crudo',
    cantidad: 100,
    calorias: 17,
    proteinas: 1.2,
    carbohidratos: 3,
    grasas: 0.3,
    unidadMedida: 'gramo',
    grupoId: 11,
  },
  {
    nombre: 'Zapallo (tipo Plomo / Anco) crudo',
    cantidad: 100,
    calorias: 26,
    proteinas: 1,
    carbohidratos: 6,
    grasas: 0.1,
    unidadMedida: 'gramo',
    grupoId: 11,
  },
  {
    nombre: 'Calabaza (zapallo coreano)',
    cantidad: 100,
    calorias: 30,
    proteinas: 1.2,
    carbohidratos: 7,
    grasas: 0.1,
    unidadMedida: 'gramo',
    grupoId: 11,
  },
  {
    nombre: 'Remolacha cruda',
    cantidad: 100,
    calorias: 43,
    proteinas: 1.6,
    carbohidratos: 10,
    grasas: 0.2,
    unidadMedida: 'gramo',
    grupoId: 11,
  },
  {
    nombre: 'Berenjena cruda',
    cantidad: 100,
    calorias: 25,
    proteinas: 1,
    carbohidratos: 6,
    grasas: 0.2,
    unidadMedida: 'gramo',
    grupoId: 11,
  },
  {
    nombre: 'Chaucha (vainita) cruda',
    cantidad: 100,
    calorias: 31,
    proteinas: 1.8,
    carbohidratos: 7,
    grasas: 0.2,
    unidadMedida: 'gramo',
    grupoId: 11,
  },
  {
    nombre: 'Choclo (maíz dulce en grano)',
    cantidad: 100,
    calorias: 86,
    proteinas: 3.2,
    carbohidratos: 19,
    grasas: 1.2,
    unidadMedida: 'gramo',
    grupoId: 11,
  },
  {
    nombre: 'Choclo entero cocido',
    cantidad: 1,
    calorias: 130,
    proteinas: 4.5,
    carbohidratos: 28,
    grasas: 2,
    unidadMedida: 'unidad',
    grupoId: 11,
  },
  {
    nombre: 'Apio crudo',
    cantidad: 100,
    calorias: 16,
    proteinas: 0.7,
    carbohidratos: 3,
    grasas: 0.2,
    unidadMedida: 'gramo',
    grupoId: 11,
  },
  {
    nombre: 'Espárrago crudo',
    cantidad: 100,
    calorias: 20,
    proteinas: 2.2,
    carbohidratos: 4,
    grasas: 0.1,
    unidadMedida: 'gramo',
    grupoId: 11,
  },
  {
    nombre: 'Hinojo crudo',
    cantidad: 100,
    calorias: 31,
    proteinas: 1.2,
    carbohidratos: 7,
    grasas: 0.2,
    unidadMedida: 'gramo',
    grupoId: 11,
  },
  {
    nombre: 'Rabanito',
    cantidad: 100,
    calorias: 16,
    proteinas: 0.7,
    carbohidratos: 3,
    grasas: 0.1,
    unidadMedida: 'gramo',
    grupoId: 11,
  },
  {
    nombre: 'Nabo crudo',
    cantidad: 100,
    calorias: 28,
    proteinas: 0.9,
    carbohidratos: 6,
    grasas: 0.1,
    unidadMedida: 'gramo',
    grupoId: 11,
  },
  {
    nombre: 'Pepino',
    cantidad: 100,
    calorias: 15,
    proteinas: 0.7,
    carbohidratos: 3,
    grasas: 0.1,
    unidadMedida: 'gramo',
    grupoId: 11,
  },

  // ========== GRUPO 12: Frutos secos y semillas ==========
  {
    nombre: 'Maní tostado salado',
    cantidad: 100,
    calorias: 567,
    proteinas: 26,
    carbohidratos: 16,
    grasas: 49,
    unidadMedida: 'gramo',
    grupoId: 12,
  },
  {
    nombre: 'Almendra cruda',
    cantidad: 100,
    calorias: 579,
    proteinas: 21,
    carbohidratos: 22,
    grasas: 50,
    unidadMedida: 'gramo',
    grupoId: 12,
  },
  {
    nombre: 'Nuez (pecán) cruda',
    cantidad: 100,
    calorias: 654,
    proteinas: 15,
    carbohidratos: 14,
    grasas: 65,
    unidadMedida: 'gramo',
    grupoId: 12,
  },
  {
    nombre: 'Avellana cruda',
    cantidad: 100,
    calorias: 628,
    proteinas: 15,
    carbohidratos: 17,
    grasas: 61,
    unidadMedida: 'gramo',
    grupoId: 12,
  },
  {
    nombre: 'Castaña de cajú (anacardo)',
    cantidad: 100,
    calorias: 553,
    proteinas: 18,
    carbohidratos: 30,
    grasas: 44,
    unidadMedida: 'gramo',
    grupoId: 12,
  },
  {
    nombre: 'Pistacho sin cáscara',
    cantidad: 100,
    calorias: 560,
    proteinas: 20,
    carbohidratos: 28,
    grasas: 45,
    unidadMedida: 'gramo',
    grupoId: 12,
  },
  {
    nombre: 'Semillas de chía',
    cantidad: 100,
    calorias: 486,
    proteinas: 17,
    carbohidratos: 42,
    grasas: 31,
    unidadMedida: 'gramo',
    grupoId: 12,
  },
  {
    nombre: 'Semillas de sésamo (ajonjolí)',
    cantidad: 100,
    calorias: 573,
    proteinas: 18,
    carbohidratos: 23,
    grasas: 49,
    unidadMedida: 'gramo',
    grupoId: 12,
  },
  {
    nombre: 'Semillas de girasol (peladas)',
    cantidad: 100,
    calorias: 584,
    proteinas: 21,
    carbohidratos: 20,
    grasas: 51,
    unidadMedida: 'gramo',
    grupoId: 12,
  },
  {
    nombre: 'Semillas de calabaza (pepitas)',
    cantidad: 100,
    calorias: 559,
    proteinas: 30,
    carbohidratos: 11,
    grasas: 49,
    unidadMedida: 'gramo',
    grupoId: 12,
  },
  {
    nombre: 'Semillas de lino (linaza)',
    cantidad: 100,
    calorias: 534,
    proteinas: 18,
    carbohidratos: 29,
    grasas: 42,
    unidadMedida: 'gramo',
    grupoId: 12,
  },
  {
    nombre: 'Pasta de maní (sin azúcar)',
    cantidad: 100,
    calorias: 588,
    proteinas: 25,
    carbohidratos: 20,
    grasas: 50,
    unidadMedida: 'gramo',
    grupoId: 12,
  },
  {
    nombre: 'Pasta de almendras',
    cantidad: 100,
    calorias: 615,
    proteinas: 21,
    carbohidratos: 20,
    grasas: 56,
    unidadMedida: 'gramo',
    grupoId: 12,
  },

  // ========== GRUPO 13: Carne vacuna y derivados (cortes argentinos) ==========
  {
    nombre: 'Lomo (solomillo)',
    cantidad: 100,
    calorias: 180,
    proteinas: 28,
    carbohidratos: 0,
    grasas: 7,
    unidadMedida: 'gramo',
    grupoId: 13,
  },
  {
    nombre: 'Bife de chorizo (bife angosto deshuesado)',
    cantidad: 100,
    calorias: 220,
    proteinas: 25,
    carbohidratos: 0,
    grasas: 13,
    unidadMedida: 'gramo',
    grupoId: 13,
  },
  {
    nombre: 'Bife ancho (con hueso)',
    cantidad: 100,
    calorias: 240,
    proteinas: 23,
    carbohidratos: 0,
    grasas: 16,
    unidadMedida: 'gramo',
    grupoId: 13,
  },
  {
    nombre: 'Bola de lomo',
    cantidad: 100,
    calorias: 170,
    proteinas: 30,
    carbohidratos: 0,
    grasas: 5,
    unidadMedida: 'gramo',
    grupoId: 13,
  },
  {
    nombre: 'Cuadril (colita de cuadril)',
    cantidad: 100,
    calorias: 160,
    proteinas: 29,
    carbohidratos: 0,
    grasas: 4.5,
    unidadMedida: 'gramo',
    grupoId: 13,
  },
  {
    nombre: 'Nalga (nalga de adentro)',
    cantidad: 100,
    calorias: 175,
    proteinas: 30,
    carbohidratos: 0,
    grasas: 5.5,
    unidadMedida: 'gramo',
    grupoId: 13,
  },
  {
    nombre: 'Peceto',
    cantidad: 100,
    calorias: 165,
    proteinas: 30,
    carbohidratos: 0,
    grasas: 4,
    unidadMedida: 'gramo',
    grupoId: 13,
  },
  {
    nombre: 'Paleta',
    cantidad: 100,
    calorias: 195,
    proteinas: 27,
    carbohidratos: 0,
    grasas: 9,
    unidadMedida: 'gramo',
    grupoId: 13,
  },
  {
    nombre: 'Cuadrada (carnaza cuadrada)',
    cantidad: 100,
    calorias: 180,
    proteinas: 28,
    carbohidratos: 0,
    grasas: 7,
    unidadMedida: 'gramo',
    grupoId: 13,
  },
  {
    nombre: 'Mar del Plata (marucha)',
    cantidad: 100,
    calorias: 190,
    proteinas: 27,
    carbohidratos: 0,
    grasas: 8.5,
    unidadMedida: 'gramo',
    grupoId: 13,
  },
  {
    nombre: 'Tapa de nalga',
    cantidad: 100,
    calorias: 170,
    proteinas: 29,
    carbohidratos: 0,
    grasas: 5,
    unidadMedida: 'gramo',
    grupoId: 13,
  },
  {
    nombre: 'Tortuguita (garrón)',
    cantidad: 100,
    calorias: 200,
    proteinas: 26,
    carbohidratos: 0,
    grasas: 10,
    unidadMedida: 'gramo',
    grupoId: 13,
  },
  {
    nombre: 'Vacío (matambre de vaca)',
    cantidad: 100,
    calorias: 250,
    proteinas: 24,
    carbohidratos: 0,
    grasas: 17,
    unidadMedida: 'gramo',
    grupoId: 13,
  },
  {
    nombre: 'Matambre',
    cantidad: 100,
    calorias: 200,
    proteinas: 27,
    carbohidratos: 0,
    grasas: 10,
    unidadMedida: 'gramo',
    grupoId: 13,
  },
  {
    nombre: 'Entraña',
    cantidad: 100,
    calorias: 240,
    proteinas: 22,
    carbohidratos: 0,
    grasas: 16,
    unidadMedida: 'gramo',
    grupoId: 13,
  },
  {
    nombre: 'Tira de asado (costillar)',
    cantidad: 100,
    calorias: 280,
    proteinas: 22,
    carbohidratos: 0,
    grasas: 21,
    unidadMedida: 'gramo',
    grupoId: 13,
  },
  {
    nombre: 'Osobuco',
    cantidad: 100,
    calorias: 210,
    proteinas: 26,
    carbohidratos: 0,
    grasas: 11,
    unidadMedida: 'gramo',
    grupoId: 13,
  },
  {
    nombre: 'Aguja (cogote)',
    cantidad: 100,
    calorias: 200,
    proteinas: 26,
    carbohidratos: 0,
    grasas: 10,
    unidadMedida: 'gramo',
    grupoId: 13,
  },
  {
    nombre: 'Falda con hueso',
    cantidad: 100,
    calorias: 265,
    proteinas: 22,
    carbohidratos: 0,
    grasas: 19,
    unidadMedida: 'gramo',
    grupoId: 13,
  },
  {
    nombre: 'Palomita de paleta',
    cantidad: 100,
    calorias: 185,
    proteinas: 28,
    carbohidratos: 0,
    grasas: 7.5,
    unidadMedida: 'gramo',
    grupoId: 13,
  },
  {
    nombre: 'Carne vacuna picada (magra)',
    cantidad: 100,
    calorias: 215,
    proteinas: 25,
    carbohidratos: 0,
    grasas: 12,
    unidadMedida: 'gramo',
    grupoId: 13,
  },
  {
    nombre: 'Carne vacuna picada (común)',
    cantidad: 100,
    calorias: 260,
    proteinas: 22,
    carbohidratos: 0,
    grasas: 19,
    unidadMedida: 'gramo',
    grupoId: 13,
  },
  {
    nombre: 'Hígado vacuno',
    cantidad: 100,
    calorias: 135,
    proteinas: 21,
    carbohidratos: 5,
    grasas: 4,
    unidadMedida: 'gramo',
    grupoId: 13,
  },
  {
    nombre: 'Riñón vacuno',
    cantidad: 100,
    calorias: 100,
    proteinas: 17,
    carbohidratos: 1,
    grasas: 3,
    unidadMedida: 'gramo',
    grupoId: 13,
  },
  {
    nombre: 'Lengua vacuna',
    cantidad: 100,
    calorias: 220,
    proteinas: 16,
    carbohidratos: 3,
    grasas: 16,
    unidadMedida: 'gramo',
    grupoId: 13,
  },

  // ========== GRUPO 14: Bebidas e infusiones ==========
  {
    nombre: 'Agua mineral natural',
    cantidad: 100,
    calorias: 0,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 0,
    unidadMedida: 'mililitro',
    grupoId: 14,
  },
  {
    nombre: 'Agua con gas (soda)',
    cantidad: 100,
    calorias: 0,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 0,
    unidadMedida: 'mililitro',
    grupoId: 14,
  },
  {
    nombre: 'Café filtrado (sin azúcar)',
    cantidad: 100,
    calorias: 2,
    proteinas: 0.3,
    carbohidratos: 0,
    grasas: 0,
    unidadMedida: 'mililitro',
    grupoId: 14,
  },
  {
    nombre: 'Café instantáneo (Nescafé)',
    cantidad: 100,
    calorias: 2,
    proteinas: 0.2,
    carbohidratos: 0.3,
    grasas: 0,
    unidadMedida: 'mililitro',
    grupoId: 14,
  },
  {
    nombre: 'Café con leche (sin azúcar)',
    cantidad: 100,
    calorias: 40,
    proteinas: 2.5,
    carbohidratos: 3,
    grasas: 2,
    unidadMedida: 'mililitro',
    grupoId: 14,
  },
  {
    nombre: 'Té negro (infusión, sin azúcar)',
    cantidad: 100,
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.3,
    grasas: 0,
    unidadMedida: 'mililitro',
    grupoId: 14,
  },
  {
    nombre: 'Té verde (infusión, sin azúcar)',
    cantidad: 100,
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 0,
    unidadMedida: 'mililitro',
    grupoId: 14,
  },
  {
    nombre: 'Mate cebado (yerba + agua)',
    cantidad: 100,
    calorias: 3,
    proteinas: 0.2,
    carbohidratos: 0.5,
    grasas: 0,
    unidadMedida: 'mililitro',
    grupoId: 14,
  },
  {
    nombre: 'Mate cocido (leche, sin azúcar)',
    cantidad: 100,
    calorias: 40,
    proteinas: 2,
    carbohidratos: 3,
    grasas: 2,
    unidadMedida: 'mililitro',
    grupoId: 14,
  },
  {
    nombre: 'Coca-Cola (original)',
    cantidad: 100,
    calorias: 42,
    proteinas: 0,
    carbohidratos: 11,
    grasas: 0,
    unidadMedida: 'mililitro',
    grupoId: 14,
  },
  {
    nombre: 'Coca-Cola Light (sin azúcar)',
    cantidad: 100,
    calorias: 0.3,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 0,
    unidadMedida: 'mililitro',
    grupoId: 14,
  },
  {
    nombre: 'Sprite',
    cantidad: 100,
    calorias: 41,
    proteinas: 0,
    carbohidratos: 10,
    grasas: 0,
    unidadMedida: 'mililitro',
    grupoId: 14,
  },
  {
    nombre: 'Jugo en polvo (Tang) preparado',
    cantidad: 100,
    calorias: 35,
    proteinas: 0,
    carbohidratos: 9,
    grasas: 0,
    unidadMedida: 'mililitro',
    grupoId: 14,
  },
  {
    nombre: 'Bebida isotónica (Gatorade)',
    cantidad: 100,
    calorias: 26,
    proteinas: 0,
    carbohidratos: 6,
    grasas: 0,
    unidadMedida: 'mililitro',
    grupoId: 14,
  },
  {
    nombre: 'Agua tónica (Schweppes)',
    cantidad: 100,
    calorias: 34,
    proteinas: 0,
    carbohidratos: 9,
    grasas: 0,
    unidadMedida: 'mililitro',
    grupoId: 14,
  },
  {
    nombre: 'Cerveza rubia (Quilmes)',
    cantidad: 100,
    calorias: 42,
    proteinas: 0.5,
    carbohidratos: 3.5,
    grasas: 0,
    unidadMedida: 'mililitro',
    grupoId: 14,
  },
  {
    nombre: 'Cerveza negra (Quilmes Bock)',
    cantidad: 100,
    calorias: 50,
    proteinas: 0.6,
    carbohidratos: 5,
    grasas: 0,
    unidadMedida: 'mililitro',
    grupoId: 14,
  },
  {
    nombre: 'Vino tinto (Mendoza - Malbec)',
    cantidad: 100,
    calorias: 85,
    proteinas: 0.1,
    carbohidratos: 2.6,
    grasas: 0,
    unidadMedida: 'mililitro',
    grupoId: 14,
  },
  {
    nombre: 'Vino blanco (Torrontés)',
    cantidad: 100,
    calorias: 82,
    proteinas: 0.1,
    carbohidratos: 2.5,
    grasas: 0,
    unidadMedida: 'mililitro',
    grupoId: 14,
  },
  {
    nombre: 'Fernet Branca',
    cantidad: 100,
    calorias: 280,
    proteinas: 0,
    carbohidratos: 25,
    grasas: 0,
    unidadMedida: 'mililitro',
    grupoId: 14,
  },
  {
    nombre: 'Vodka',
    cantidad: 100,
    calorias: 231,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 0,
    unidadMedida: 'mililitro',
    grupoId: 14,
  },
  {
    nombre: 'Ron',
    cantidad: 100,
    calorias: 240,
    proteinas: 0,
    carbohidratos: 3,
    grasas: 0,
    unidadMedida: 'mililitro',
    grupoId: 14,
  },
  {
    nombre: 'Whisky',
    cantidad: 100,
    calorias: 244,
    proteinas: 0,
    carbohidratos: 0.1,
    grasas: 0,
    unidadMedida: 'mililitro',
    grupoId: 14,
  },

  // ========== GRUPO 15: Pescados y mariscos ==========
  {
    nombre: 'Merluza (filete crudo)',
    cantidad: 100,
    calorias: 90,
    proteinas: 19,
    carbohidratos: 0,
    grasas: 1,
    unidadMedida: 'gramo',
    grupoId: 15,
  },
  {
    nombre: 'Atún en agua (enlatado, escurrido)',
    cantidad: 100,
    calorias: 120,
    proteinas: 26,
    carbohidratos: 0,
    grasas: 1.5,
    unidadMedida: 'gramo',
    grupoId: 15,
  },
  {
    nombre: 'Atún en aceite (enlatado, escurrido)',
    cantidad: 100,
    calorias: 200,
    proteinas: 24,
    carbohidratos: 0,
    grasas: 11,
    unidadMedida: 'gramo',
    grupoId: 15,
  },
  {
    nombre: 'Salmón rosado (crudo)',
    cantidad: 100,
    calorias: 180,
    proteinas: 22,
    carbohidratos: 0,
    grasas: 10,
    unidadMedida: 'gramo',
    grupoId: 15,
  },
  {
    nombre: 'Salmón ahumado (feteado)',
    cantidad: 100,
    calorias: 180,
    proteinas: 22,
    carbohidratos: 0,
    grasas: 10,
    unidadMedida: 'gramo',
    grupoId: 15,
  },
  {
    nombre: 'Trucha arcoíris (cruda)',
    cantidad: 100,
    calorias: 130,
    proteinas: 21,
    carbohidratos: 0,
    grasas: 5,
    unidadMedida: 'gramo',
    grupoId: 15,
  },
  {
    nombre: 'Caballa (cruda)',
    cantidad: 100,
    calorias: 180,
    proteinas: 20,
    carbohidratos: 0,
    grasas: 11,
    unidadMedida: 'gramo',
    grupoId: 15,
  },
  {
    nombre: 'Cazón (crudo)',
    cantidad: 100,
    calorias: 130,
    proteinas: 21,
    carbohidratos: 0,
    grasas: 5,
    unidadMedida: 'gramo',
    grupoId: 15,
  },
  {
    nombre: 'Lenguado (filete crudo)',
    cantidad: 100,
    calorias: 85,
    proteinas: 18,
    carbohidratos: 0,
    grasas: 1.5,
    unidadMedida: 'gramo',
    grupoId: 15,
  },
  {
    nombre: 'Sardina en aceite (enlatada)',
    cantidad: 100,
    calorias: 220,
    proteinas: 24,
    carbohidratos: 0,
    grasas: 13,
    unidadMedida: 'gramo',
    grupoId: 15,
  },
  {
    nombre: 'Camarones (crudos, pelados)',
    cantidad: 100,
    calorias: 85,
    proteinas: 18,
    carbohidratos: 1,
    grasas: 0.8,
    unidadMedida: 'gramo',
    grupoId: 15,
  },
  {
    nombre: 'Langostinos (crudos)',
    cantidad: 100,
    calorias: 90,
    proteinas: 19,
    carbohidratos: 0.5,
    grasas: 1,
    unidadMedida: 'gramo',
    grupoId: 15,
  },
  {
    nombre: 'Calamar (anillos, crudo)',
    cantidad: 100,
    calorias: 80,
    proteinas: 15,
    carbohidratos: 2,
    grasas: 1,
    unidadMedida: 'gramo',
    grupoId: 15,
  },
  {
    nombre: 'Mejillones (cocidos al vapor)',
    cantidad: 100,
    calorias: 90,
    proteinas: 12,
    carbohidratos: 4,
    grasas: 2.5,
    unidadMedida: 'gramo',
    grupoId: 15,
  },
  {
    nombre: 'Abadejo (filete crudo)',
    cantidad: 100,
    calorias: 85,
    proteinas: 18,
    carbohidratos: 0,
    grasas: 0.7,
    unidadMedida: 'gramo',
    grupoId: 15,
  },

  // ========== GRUPO 16: Legumbres y harinas de legumbres ==========
  {
    nombre: 'Lentejas secas',
    cantidad: 100,
    calorias: 350,
    proteinas: 25,
    carbohidratos: 60,
    grasas: 1,
    unidadMedida: 'gramo',
    grupoId: 16,
  },
  {
    nombre: 'Lentejas cocidas',
    cantidad: 100,
    calorias: 116,
    proteinas: 9,
    carbohidratos: 20,
    grasas: 0,
    unidadMedida: 'gramo',
    grupoId: 16,
  },
  {
    nombre: 'Garbanzos secos',
    cantidad: 100,
    calorias: 360,
    proteinas: 20,
    carbohidratos: 60,
    grasas: 5.5,
    unidadMedida: 'gramo',
    grupoId: 16,
  },
  {
    nombre: 'Garbanzos cocidos',
    cantidad: 100,
    calorias: 130,
    proteinas: 7.5,
    carbohidratos: 22,
    grasas: 2,
    unidadMedida: 'gramo',
    grupoId: 16,
  },
  {
    nombre: 'Porotos (frijoles) secos',
    cantidad: 100,
    calorias: 340,
    proteinas: 22,
    carbohidratos: 60,
    grasas: 1.5,
    unidadMedida: 'gramo',
    grupoId: 16,
  },
  {
    nombre: 'Porotos (frijoles) cocidos',
    cantidad: 100,
    calorias: 120,
    proteinas: 8,
    carbohidratos: 21,
    grasas: 0.5,
    unidadMedida: 'gramo',
    grupoId: 16,
  },
  {
    nombre: 'Habas secas',
    cantidad: 100,
    calorias: 340,
    proteinas: 26,
    carbohidratos: 58,
    grasas: 1.4,
    unidadMedida: 'gramo',
    grupoId: 16,
  },
  {
    nombre: 'Soja (poroto de soja) seca',
    cantidad: 100,
    calorias: 446,
    proteinas: 36,
    carbohidratos: 30,
    grasas: 20,
    unidadMedida: 'gramo',
    grupoId: 16,
  },
  {
    nombre: 'Arvejas verdes secas',
    cantidad: 100,
    calorias: 340,
    proteinas: 24,
    carbohidratos: 60,
    grasas: 1.2,
    unidadMedida: 'gramo',
    grupoId: 16,
  },
  {
    nombre: 'Arvejas enlatadas (escurridas)',
    cantidad: 100,
    calorias: 80,
    proteinas: 5,
    carbohidratos: 14,
    grasas: 0.3,
    unidadMedida: 'gramo',
    grupoId: 16,
  },
  {
    nombre: 'Harina de garbanzo',
    cantidad: 100,
    calorias: 365,
    proteinas: 22,
    carbohidratos: 58,
    grasas: 6,
    unidadMedida: 'gramo',
    grupoId: 16,
  },
  {
    nombre: 'Harina de soja',
    cantidad: 100,
    calorias: 420,
    proteinas: 38,
    carbohidratos: 30,
    grasas: 20,
    unidadMedida: 'gramo',
    grupoId: 16,
  },

  // ========== GRUPO 17: Otras carnes (cordero, chivito, caza) ==========
  {
    nombre: 'Cordero (pierna, cruda)',
    cantidad: 100,
    calorias: 240,
    proteinas: 23,
    carbohidratos: 0,
    grasas: 16,
    unidadMedida: 'gramo',
    grupoId: 17,
  },
  {
    nombre: 'Cordero (costillar, crudo)',
    cantidad: 100,
    calorias: 280,
    proteinas: 20,
    carbohidratos: 0,
    grasas: 22,
    unidadMedida: 'gramo',
    grupoId: 17,
  },
  {
    nombre: 'Chivito (cabrito, crudo)',
    cantidad: 100,
    calorias: 200,
    proteinas: 24,
    carbohidratos: 0,
    grasas: 11,
    unidadMedida: 'gramo',
    grupoId: 17,
  },
  {
    nombre: 'Conejo (carne cruda)',
    cantidad: 100,
    calorias: 170,
    proteinas: 24,
    carbohidratos: 0,
    grasas: 8,
    unidadMedida: 'gramo',
    grupoId: 17,
  },
  {
    nombre: 'Ciervo (carne de venado, cruda)',
    cantidad: 100,
    calorias: 150,
    proteinas: 28,
    carbohidratos: 0,
    grasas: 3.5,
    unidadMedida: 'gramo',
    grupoId: 17,
  },
  {
    nombre: 'Jabalí (carne cruda)',
    cantidad: 100,
    calorias: 160,
    proteinas: 26,
    carbohidratos: 0,
    grasas: 5.5,
    unidadMedida: 'gramo',
    grupoId: 17,
  },
  {
    nombre: 'Liebre (carne cruda)',
    cantidad: 100,
    calorias: 150,
    proteinas: 27,
    carbohidratos: 0,
    grasas: 4,
    unidadMedida: 'gramo',
    grupoId: 17,
  },

  // ========== GRUPO 18: Panificados, galletas y repostería ==========
  {
    nombre: 'Pan francés (flauta / mignon)',
    cantidad: 100,
    calorias: 272,
    proteinas: 8,
    carbohidratos: 57,
    grasas: 1,
    unidadMedida: 'gramo',
    grupoId: 18,
  },
  {
    nombre: 'Pan de viena (salvado)',
    cantidad: 100,
    calorias: 250,
    proteinas: 9,
    carbohidratos: 48,
    grasas: 3.5,
    unidadMedida: 'gramo',
    grupoId: 18,
  },
  {
    nombre: 'Pan de salvado',
    cantidad: 100,
    calorias: 220,
    proteinas: 8,
    carbohidratos: 40,
    grasas: 4,
    unidadMedida: 'gramo',
    grupoId: 18,
  },
  {
    nombre: 'Pan integral',
    cantidad: 100,
    calorias: 230,
    proteinas: 9,
    carbohidratos: 42,
    grasas: 3,
    unidadMedida: 'gramo',
    grupoId: 18,
  },
  {
    nombre: 'Pan lactal (Bimbo / Fargo)',
    cantidad: 100,
    calorias: 260,
    proteinas: 8,
    carbohidratos: 48,
    grasas: 3.5,
    unidadMedida: 'gramo',
    grupoId: 18,
  },
  {
    nombre: 'Panelas (galletas de agua) (Bagley)',
    cantidad: 100,
    calorias: 380,
    proteinas: 11,
    carbohidratos: 75,
    grasas: 4,
    unidadMedida: 'gramo',
    grupoId: 18,
  },
  {
    nombre: 'Galletas de arroz (Arrocito)',
    cantidad: 100,
    calorias: 370,
    proteinas: 8,
    carbohidratos: 80,
    grasas: 1.5,
    unidadMedida: 'gramo',
    grupoId: 18,
  },
  {
    nombre: 'Criollitas (Bagley)',
    cantidad: 100,
    calorias: 450,
    proteinas: 8,
    carbohidratos: 68,
    grasas: 17,
    unidadMedida: 'gramo',
    grupoId: 18,
  },
  {
    nombre: 'Express (Bagley - galletas dulces)',
    cantidad: 100,
    calorias: 480,
    proteinas: 6,
    carbohidratos: 70,
    grasas: 20,
    unidadMedida: 'gramo',
    grupoId: 18,
  },
  {
    nombre: 'Rumba (Terrabusi / Mondelez)',
    cantidad: 100,
    calorias: 480,
    proteinas: 6,
    carbohidratos: 65,
    grasas: 22,
    unidadMedida: 'gramo',
    grupoId: 18,
  },
  {
    nombre: 'Oreo (Mondelez)',
    cantidad: 100,
    calorias: 480,
    proteinas: 5,
    carbohidratos: 68,
    grasas: 21,
    unidadMedida: 'gramo',
    grupoId: 18,
  },
  {
    nombre: 'Chocolinas (Terrabusi)',
    cantidad: 100,
    calorias: 470,
    proteinas: 6,
    carbohidratos: 70,
    grasas: 19,
    unidadMedida: 'gramo',
    grupoId: 18,
  },
  {
    nombre: 'Melba (Terrabusi)',
    cantidad: 100,
    calorias: 460,
    proteinas: 5.5,
    carbohidratos: 72,
    grasas: 17,
    unidadMedida: 'gramo',
    grupoId: 18,
  },
  {
    nombre: 'Pepas (Terrabusi)',
    cantidad: 100,
    calorias: 440,
    proteinas: 5,
    carbohidratos: 70,
    grasas: 16,
    unidadMedida: 'gramo',
    grupoId: 18,
  },
  {
    nombre: 'Surtido Bagley (galletitas dulces)',
    cantidad: 100,
    calorias: 470,
    proteinas: 6,
    carbohidratos: 68,
    grasas: 19,
    unidadMedida: 'gramo',
    grupoId: 18,
  },
  {
    nombre: 'Masitas de agua',
    cantidad: 100,
    calorias: 420,
    proteinas: 9,
    carbohidratos: 72,
    grasas: 10,
    unidadMedida: 'gramo',
    grupoId: 18,
  },
  {
    nombre: 'Medialuna de manteca',
    cantidad: 1,
    calorias: 150,
    proteinas: 3.5,
    carbohidratos: 20,
    grasas: 6.5,
    unidadMedida: 'unidad',
    grupoId: 18,
  },
  {
    nombre: 'Bizcochuelo (vaina)',
    cantidad: 100,
    calorias: 350,
    proteinas: 6,
    carbohidratos: 70,
    grasas: 5,
    unidadMedida: 'gramo',
    grupoId: 18,
  },
  {
    nombre: 'Budín de pan (casero)',
    cantidad: 100,
    calorias: 270,
    proteinas: 7,
    carbohidratos: 40,
    grasas: 10,
    unidadMedida: 'gramo',
    grupoId: 18,
  },
  {
    nombre: 'Tarta de ricota (dulce)',
    cantidad: 100,
    calorias: 280,
    proteinas: 8,
    carbohidratos: 35,
    grasas: 12,
    unidadMedida: 'gramo',
    grupoId: 18,
  },
  {
    nombre: 'FACTURA (vigilante / cañoncito)',
    cantidad: 1,
    calorias: 180,
    proteinas: 4,
    carbohidratos: 25,
    grasas: 7,
    unidadMedida: 'unidad',
    grupoId: 18,
  },
  {
    nombre: 'Pan de hamburguesa (Bimbo)',
    cantidad: 1,
    calorias: 180,
    proteinas: 6,
    carbohidratos: 30,
    grasas: 3.5,
    unidadMedida: 'unidad',
    grupoId: 18,
  },

  // ========== GRUPO 19: Dulces, mermeladas y azúcares ==========
  {
    nombre: 'Azúcar blanca (Ledesma)',
    cantidad: 100,
    calorias: 387,
    proteinas: 0,
    carbohidratos: 100,
    grasas: 0,
    unidadMedida: 'gramo',
    grupoId: 19,
  },
  {
    nombre: 'Azúcar morena (Ledesma)',
    cantidad: 100,
    calorias: 375,
    proteinas: 0.5,
    carbohidratos: 96,
    grasas: 0,
    unidadMedida: 'gramo',
    grupoId: 19,
  },
  {
    nombre: 'Edulcorante líquido (Hileret / Sancor)',
    cantidad: 100,
    calorias: 5,
    proteinas: 0,
    carbohidratos: 0.5,
    grasas: 0,
    unidadMedida: 'mililitro',
    grupoId: 19,
  },
  {
    nombre: 'Miel de abejas (orgánica)',
    cantidad: 100,
    calorias: 304,
    proteinas: 0.3,
    carbohidratos: 82,
    grasas: 0,
    unidadMedida: 'gramo',
    grupoId: 19,
  },
  {
    nombre: 'Mermelada de frutilla (La Campagnola / Arcor)',
    cantidad: 100,
    calorias: 250,
    proteinas: 0.5,
    carbohidratos: 62,
    grasas: 0.1,
    unidadMedida: 'gramo',
    grupoId: 19,
  },
  {
    nombre: 'Mermelada de durazno (La Campagnola)',
    cantidad: 100,
    calorias: 245,
    proteinas: 0.4,
    carbohidratos: 60,
    grasas: 0.1,
    unidadMedida: 'gramo',
    grupoId: 19,
  },
  {
    nombre: 'Dulce de batata (La Campagnola)',
    cantidad: 100,
    calorias: 260,
    proteinas: 1,
    carbohidratos: 65,
    grasas: 0.2,
    unidadMedida: 'gramo',
    grupoId: 19,
  },
  {
    nombre: 'Dulce de membrillo',
    cantidad: 100,
    calorias: 250,
    proteinas: 0.5,
    carbohidratos: 63,
    grasas: 0.1,
    unidadMedida: 'gramo',
    grupoId: 19,
  },
  {
    nombre: 'Cacao en polvo (Arcor)',
    cantidad: 100,
    calorias: 330,
    proteinas: 20,
    carbohidratos: 55,
    grasas: 6,
    unidadMedida: 'gramo',
    grupoId: 19,
  },
  {
    nombre: 'Chocolate con leche (Arcor)',
    cantidad: 100,
    calorias: 540,
    proteinas: 7,
    carbohidratos: 55,
    grasas: 32,
    unidadMedida: 'gramo',
    grupoId: 19,
  },
  {
    nombre: 'Chocolate semiamargo (Arcor)',
    cantidad: 100,
    calorias: 520,
    proteinas: 6,
    carbohidratos: 50,
    grasas: 33,
    unidadMedida: 'gramo',
    grupoId: 19,
  },
  {
    nombre: 'Chocolate blanco (Arcor)',
    cantidad: 100,
    calorias: 560,
    proteinas: 6,
    carbohidratos: 55,
    grasas: 35,
    unidadMedida: 'gramo',
    grupoId: 19,
  },
  {
    nombre: 'Bon o Bon (Arcor)',
    cantidad: 1,
    calorias: 65,
    proteinas: 1,
    carbohidratos: 8,
    grasas: 3.5,
    unidadMedida: 'unidad',
    grupoId: 19,
  },
  {
    nombre: 'Cofler Block (Arcor)',
    cantidad: 100,
    calorias: 530,
    proteinas: 7,
    carbohidratos: 58,
    grasas: 30,
    unidadMedida: 'gramo',
    grupoId: 19,
  },
  {
    nombre: 'Topline (Arcor - oblea bañada)',
    cantidad: 1,
    calorias: 80,
    proteinas: 1,
    carbohidratos: 10,
    grasas: 4,
    unidadMedida: 'unidad',
    grupoId: 19,
  },
  {
    nombre: 'Alfajor (Guaymallén)',
    cantidad: 1,
    calorias: 200,
    proteinas: 3,
    carbohidratos: 30,
    grasas: 8,
    unidadMedida: 'unidad',
    grupoId: 19,
  },
  {
    nombre: 'Alfajor (Jorgito)',
    cantidad: 1,
    calorias: 230,
    proteinas: 3.5,
    carbohidratos: 32,
    grasas: 10,
    unidadMedida: 'unidad',
    grupoId: 19,
  },
  {
    nombre: 'Alfajor (Havanna)',
    cantidad: 1,
    calorias: 280,
    proteinas: 3,
    carbohidratos: 36,
    grasas: 14,
    unidadMedida: 'unidad',
    grupoId: 19,
  },
  {
    nombre: 'Caramelo masticable (Arcor)',
    cantidad: 100,
    calorias: 380,
    proteinas: 2,
    carbohidratos: 80,
    grasas: 7,
    unidadMedida: 'gramo',
    grupoId: 19,
  },
  {
    nombre: 'Butter Toffees (Arcor)',
    cantidad: 100,
    calorias: 450,
    proteinas: 3,
    carbohidratos: 68,
    grasas: 18,
    unidadMedida: 'gramo',
    grupoId: 19,
  },
  {
    nombre: 'Rocklets (Arcor)',
    cantidad: 100,
    calorias: 500,
    proteinas: 5,
    carbohidratos: 62,
    grasas: 25,
    unidadMedida: 'gramo',
    grupoId: 19,
  },
  {
    nombre: 'Mogul (gomitas Arcor)',
    cantidad: 100,
    calorias: 340,
    proteinas: 4,
    carbohidratos: 80,
    grasas: 0.5,
    unidadMedida: 'gramo',
    grupoId: 19,
  },

  // ========== GRUPO 20: Cereales, pastas y harinas ==========
  {
    nombre: 'Arroz blanco (grano largo) crudo',
    cantidad: 100,
    calorias: 350,
    proteinas: 7,
    carbohidratos: 78,
    grasas: 0.6,
    unidadMedida: 'gramo',
    grupoId: 20,
  },
  {
    nombre: 'Arroz blanco cocido',
    cantidad: 100,
    calorias: 130,
    proteinas: 3,
    carbohidratos: 28,
    grasas: 0,
    unidadMedida: 'gramo',
    grupoId: 20,
  },
  {
    nombre: 'Arroz integral crudo',
    cantidad: 100,
    calorias: 350,
    proteinas: 7.5,
    carbohidratos: 74,
    grasas: 2.5,
    unidadMedida: 'gramo',
    grupoId: 20,
  },
  {
    nombre: 'Arroz integral cocido',
    cantidad: 100,
    calorias: 125,
    proteinas: 3,
    carbohidratos: 26,
    grasas: 1,
    unidadMedida: 'gramo',
    grupoId: 20,
  },
  {
    nombre: 'Arroz yamaní crudo',
    cantidad: 100,
    calorias: 355,
    proteinas: 8,
    carbohidratos: 75,
    grasas: 2,
    unidadMedida: 'gramo',
    grupoId: 20,
  },
  {
    nombre: 'Fideos secos (spaghetti / tallarines)',
    cantidad: 100,
    calorias: 355,
    proteinas: 12,
    carbohidratos: 73,
    grasas: 1.5,
    unidadMedida: 'gramo',
    grupoId: 20,
  },
  {
    nombre: 'Fideos cocidos (spaghetti / tallarines)',
    cantidad: 100,
    calorias: 130,
    proteinas: 4.5,
    carbohidratos: 26,
    grasas: 0.5,
    unidadMedida: 'gramo',
    grupoId: 20,
  },
  {
    nombre: 'Fideos secos (tirabuzón / mostachol)',
    cantidad: 100,
    calorias: 355,
    proteinas: 12,
    carbohidratos: 73,
    grasas: 1.5,
    unidadMedida: 'gramo',
    grupoId: 20,
  },
  {
    nombre: 'Ñoquis de papa (cocidos)',
    cantidad: 100,
    calorias: 140,
    proteinas: 4,
    carbohidratos: 28,
    grasas: 1,
    unidadMedida: 'gramo',
    grupoId: 20,
  },
  {
    nombre: 'Ravioles de verdura (frescos, cocidos)',
    cantidad: 100,
    calorias: 160,
    proteinas: 6,
    carbohidratos: 27,
    grasas: 3,
    unidadMedida: 'gramo',
    grupoId: 20,
  },
  {
    nombre: 'Ravioles de carne (frescos, cocidos)',
    cantidad: 100,
    calorias: 180,
    proteinas: 7,
    carbohidratos: 26,
    grasas: 5,
    unidadMedida: 'gramo',
    grupoId: 20,
  },
  {
    nombre: 'Harina de trigo común (0000)',
    cantidad: 100,
    calorias: 340,
    proteinas: 10,
    carbohidratos: 72,
    grasas: 1.2,
    unidadMedida: 'gramo',
    grupoId: 20,
  },
  {
    nombre: 'Harina de trigo integral',
    cantidad: 100,
    calorias: 320,
    proteinas: 12,
    carbohidratos: 65,
    grasas: 2.5,
    unidadMedida: 'gramo',
    grupoId: 20,
  },
  {
    nombre: 'Sémola de trigo',
    cantidad: 100,
    calorias: 350,
    proteinas: 12,
    carbohidratos: 72,
    grasas: 1.5,
    unidadMedida: 'gramo',
    grupoId: 20,
  },
  {
    nombre: 'Polenta (harina de maíz) cruda',
    cantidad: 100,
    calorias: 360,
    proteinas: 8,
    carbohidratos: 78,
    grasas: 1.5,
    unidadMedida: 'gramo',
    grupoId: 20,
  },
  {
    nombre: 'Polenta cocida',
    cantidad: 100,
    calorias: 80,
    proteinas: 2,
    carbohidratos: 17,
    grasas: 0.3,
    unidadMedida: 'gramo',
    grupoId: 20,
  },
  {
    nombre: 'Quinoa cruda',
    cantidad: 100,
    calorias: 365,
    proteinas: 14,
    carbohidratos: 64,
    grasas: 6,
    unidadMedida: 'gramo',
    grupoId: 20,
  },
  {
    nombre: 'Quinoa cocida',
    cantidad: 100,
    calorias: 120,
    proteinas: 4.5,
    carbohidratos: 21,
    grasas: 2,
    unidadMedida: 'gramo',
    grupoId: 20,
  },
  {
    nombre: 'Amaranto crudo',
    cantidad: 100,
    calorias: 370,
    proteinas: 14,
    carbohidratos: 65,
    grasas: 7,
    unidadMedida: 'gramo',
    grupoId: 20,
  },
  {
    nombre: 'Cebada perlada cruda',
    cantidad: 100,
    calorias: 340,
    proteinas: 10,
    carbohidratos: 72,
    grasas: 2,
    unidadMedida: 'gramo',
    grupoId: 20,
  },
  {
    nombre: 'Centeno (harina)',
    cantidad: 100,
    calorias: 330,
    proteinas: 8,
    carbohidratos: 70,
    grasas: 2,
    unidadMedida: 'gramo',
    grupoId: 20,
  },
  {
    nombre: 'Trigo burgol',
    cantidad: 100,
    calorias: 340,
    proteinas: 12,
    carbohidratos: 68,
    grasas: 2,
    unidadMedida: 'gramo',
    grupoId: 20,
  },

  // ========== GRUPO 21: Comida rápida (Fast Food) ==========
  {
    nombre: "Hamburguesa de carne (McDonald's)",
    cantidad: 1,
    calorias: 250,
    proteinas: 12,
    carbohidratos: 30,
    grasas: 9,
    unidadMedida: 'unidad',
    grupoId: 21,
  },
  {
    nombre: "Hamburguesa con queso (McDonald's)",
    cantidad: 1,
    calorias: 300,
    proteinas: 15,
    carbohidratos: 33,
    grasas: 12,
    unidadMedida: 'unidad',
    grupoId: 21,
  },
  {
    nombre: 'Pancho (salchicha + pan)',
    cantidad: 1,
    calorias: 280,
    proteinas: 10,
    carbohidratos: 25,
    grasas: 15,
    unidadMedida: 'unidad',
    grupoId: 21,
  },
  {
    nombre: "Papas fritas (porción mediana - McDonald's)",
    cantidad: 100,
    calorias: 310,
    proteinas: 4,
    carbohidratos: 40,
    grasas: 15,
    unidadMedida: 'gramo',
    grupoId: 21,
  },
  {
    nombre: 'Pizza de muzzarella (porción - grande)',
    cantidad: 1,
    calorias: 285,
    proteinas: 13,
    carbohidratos: 30,
    grasas: 12,
    unidadMedida: 'unidad',
    grupoId: 21,
  },
  {
    nombre: 'Empanada de carne frita',
    cantidad: 1,
    calorias: 250,
    proteinas: 10,
    carbohidratos: 22,
    grasas: 14,
    unidadMedida: 'unidad',
    grupoId: 21,
  },
  {
    nombre: 'Empanada de carne al horno',
    cantidad: 1,
    calorias: 200,
    proteinas: 10,
    carbohidratos: 24,
    grasas: 8,
    unidadMedida: 'unidad',
    grupoId: 21,
  },
  {
    nombre: 'Lomito completo (sandwich)',
    cantidad: 1,
    calorias: 550,
    proteinas: 30,
    carbohidratos: 40,
    grasas: 28,
    unidadMedida: 'unidad',
    grupoId: 21,
  },
  {
    nombre: 'Sandwich de miga triples (jamón y queso)',
    cantidad: 100,
    calorias: 280,
    proteinas: 12,
    carbohidratos: 30,
    grasas: 12,
    unidadMedida: 'gramo',
    grupoId: 21,
  },
  {
    nombre: "Nuggets de pollo (McDonald's, 4 unid)",
    cantidad: 100,
    calorias: 280,
    proteinas: 15,
    carbohidratos: 18,
    grasas: 17,
    unidadMedida: 'gramo',
    grupoId: 21,
  },
  {
    nombre: 'Helado de crema (pote - 1 bocha)',
    cantidad: 1,
    calorias: 180,
    proteinas: 3,
    carbohidratos: 22,
    grasas: 9,
    unidadMedida: 'unidad',
    grupoId: 21,
  },

  // ========== GRUPO 22: Platos elaborados y guarniciones ==========
  {
    nombre: 'Milanesa de carne (frita)',
    cantidad: 1,
    calorias: 350,
    proteinas: 25,
    carbohidratos: 16,
    grasas: 20,
    unidadMedida: 'unidad',
    grupoId: 22,
  },
  {
    nombre: 'Milanesa de carne (al horno)',
    cantidad: 1,
    calorias: 280,
    proteinas: 28,
    carbohidratos: 16,
    grasas: 12,
    unidadMedida: 'unidad',
    grupoId: 22,
  },
  {
    nombre: 'Milanesa de pollo (frita)',
    cantidad: 1,
    calorias: 310,
    proteinas: 24,
    carbohidratos: 15,
    grasas: 17,
    unidadMedida: 'unidad',
    grupoId: 22,
  },
  {
    nombre: 'Milanesa napolitana (carne, frita)',
    cantidad: 1,
    calorias: 420,
    proteinas: 28,
    carbohidratos: 20,
    grasas: 25,
    unidadMedida: 'unidad',
    grupoId: 22,
  },
  {
    nombre: 'Puré de papas (casero, con leche y manteca)',
    cantidad: 100,
    calorias: 120,
    proteinas: 2.5,
    carbohidratos: 20,
    grasas: 4,
    unidadMedida: 'gramo',
    grupoId: 22,
  },
  {
    nombre: 'Ensalada rusa (papa, zanahoria, arvejas, mayonesa)',
    cantidad: 100,
    calorias: 150,
    proteinas: 2,
    carbohidratos: 15,
    grasas: 9,
    unidadMedida: 'gramo',
    grupoId: 22,
  },
  {
    nombre: 'Guiso de lentejas (casero)',
    cantidad: 100,
    calorias: 110,
    proteinas: 7,
    carbohidratos: 15,
    grasas: 3,
    unidadMedida: 'gramo',
    grupoId: 22,
  },
  {
    nombre: 'Locro (casero)',
    cantidad: 100,
    calorias: 130,
    proteinas: 7,
    carbohidratos: 18,
    grasas: 4,
    unidadMedida: 'gramo',
    grupoId: 22,
  },
  {
    nombre: 'Puchero (casero)',
    cantidad: 100,
    calorias: 90,
    proteinas: 6,
    carbohidratos: 8,
    grasas: 4,
    unidadMedida: 'gramo',
    grupoId: 22,
  },
  {
    nombre: 'Tarta de verdura (pascualina)',
    cantidad: 100,
    calorias: 200,
    proteinas: 7,
    carbohidratos: 20,
    grasas: 10,
    unidadMedida: 'gramo',
    grupoId: 22,
  },
  {
    nombre: 'Canelones de verdura (con salsa)',
    cantidad: 100,
    calorias: 180,
    proteinas: 7,
    carbohidratos: 20,
    grasas: 8,
    unidadMedida: 'gramo',
    grupoId: 22,
  },
  {
    nombre: 'Pastel de papas (casero)',
    cantidad: 100,
    calorias: 160,
    proteinas: 8,
    carbohidratos: 16,
    grasas: 7,
    unidadMedida: 'gramo',
    grupoId: 22,
  },
  {
    nombre: 'Ensalada de lechuga y tomate (sin aderezo)',
    cantidad: 100,
    calorias: 20,
    proteinas: 1,
    carbohidratos: 4,
    grasas: 0.2,
    unidadMedida: 'gramo',
    grupoId: 22,
  },

  // ========== GRUPO 23: Snacks y copetín ==========
  {
    nombre: 'Papas fritas de paquete (Lays)',
    cantidad: 100,
    calorias: 530,
    proteinas: 6,
    carbohidratos: 50,
    grasas: 34,
    unidadMedida: 'gramo',
    grupoId: 23,
  },
  {
    nombre: 'Papas fritas sabor a la crema (Lays)',
    cantidad: 100,
    calorias: 540,
    proteinas: 6,
    carbohidratos: 50,
    grasas: 35,
    unidadMedida: 'gramo',
    grupoId: 23,
  },
  {
    nombre: 'Doritos (sabor queso)',
    cantidad: 100,
    calorias: 500,
    proteinas: 7,
    carbohidratos: 55,
    grasas: 28,
    unidadMedida: 'gramo',
    grupoId: 23,
  },
  {
    nombre: 'Cheetos (saladitos / queso)',
    cantidad: 100,
    calorias: 520,
    proteinas: 6,
    carbohidratos: 52,
    grasas: 32,
    unidadMedida: 'gramo',
    grupoId: 23,
  },
  {
    nombre: 'Palitos salados (Saladix)',
    cantidad: 100,
    calorias: 410,
    proteinas: 10,
    carbohidratos: 72,
    grasas: 8,
    unidadMedida: 'gramo',
    grupoId: 23,
  },
  {
    nombre: 'Maní salado (envasado)',
    cantidad: 100,
    calorias: 560,
    proteinas: 26,
    carbohidratos: 16,
    grasas: 49,
    unidadMedida: 'gramo',
    grupoId: 23,
  },
  {
    nombre: 'Pochoclo (palomitas de maíz - microondas)',
    cantidad: 100,
    calorias: 380,
    proteinas: 8,
    carbohidratos: 45,
    grasas: 18,
    unidadMedida: 'gramo',
    grupoId: 23,
  },
  {
    nombre: 'Pochoclo natural (sin grasa)',
    cantidad: 100,
    calorias: 330,
    proteinas: 10,
    carbohidratos: 60,
    grasas: 4,
    unidadMedida: 'gramo',
    grupoId: 23,
  },
  {
    nombre: 'Pretzels (palitos salados horneados)',
    cantidad: 100,
    calorias: 380,
    proteinas: 10,
    carbohidratos: 80,
    grasas: 3,
    unidadMedida: 'gramo',
    grupoId: 23,
  },
  {
    nombre: 'Nachos (tortilla chips)',
    cantidad: 100,
    calorias: 490,
    proteinas: 7,
    carbohidratos: 56,
    grasas: 27,
    unidadMedida: 'gramo',
    grupoId: 23,
  },
  {
    nombre: 'Crackers de arroz (snack salado)',
    cantidad: 100,
    calorias: 400,
    proteinas: 7,
    carbohidratos: 72,
    grasas: 8,
    unidadMedida: 'gramo',
    grupoId: 23,
  },
  {
    nombre: 'Pipas (semillas de girasol con cáscara)',
    cantidad: 100,
    calorias: 580,
    proteinas: 20,
    carbohidratos: 20,
    grasas: 50,
    unidadMedida: 'gramo',
    grupoId: 23,
  },

  // ========== GRUPO 24: Alimentos regionales y autóctonos ==========
  {
    nombre: 'Yerba mate (canchada)',
    cantidad: 100,
    calorias: 250,
    proteinas: 12,
    carbohidratos: 50,
    grasas: 3,
    unidadMedida: 'gramo',
    grupoId: 24,
  },
  {
    nombre: 'Dulce de batata (en bloque)',
    cantidad: 100,
    calorias: 260,
    proteinas: 1,
    carbohidratos: 65,
    grasas: 0.2,
    unidadMedida: 'gramo',
    grupoId: 24,
  },
  {
    nombre: 'Dulce de membrillo (en bloque)',
    cantidad: 100,
    calorias: 250,
    proteinas: 0.5,
    carbohidratos: 63,
    grasas: 0.1,
    unidadMedida: 'gramo',
    grupoId: 24,
  },
  {
    nombre: 'Chipá (de almidón de mandioca)',
    cantidad: 1,
    calorias: 80,
    proteinas: 2,
    carbohidratos: 10,
    grasas: 3.5,
    unidadMedida: 'unidad',
    grupoId: 24,
  },
  {
    nombre: 'Tortilla de papa (española)',
    cantidad: 100,
    calorias: 180,
    proteinas: 8,
    carbohidratos: 15,
    grasas: 10,
    unidadMedida: 'gramo',
    grupoId: 24,
  },
  {
    nombre: 'Humita en chala (casera)',
    cantidad: 100,
    calorias: 140,
    proteinas: 4,
    carbohidratos: 20,
    grasas: 5,
    unidadMedida: 'gramo',
    grupoId: 24,
  },
  {
    nombre: 'Tamal (casero)',
    cantidad: 1,
    calorias: 200,
    proteinas: 6,
    carbohidratos: 28,
    grasas: 8,
    unidadMedida: 'unidad',
    grupoId: 24,
  },
  {
    nombre: 'Postre vigilante (dulce de batata + queso)',
    cantidad: 100,
    calorias: 200,
    proteinas: 6,
    carbohidratos: 32,
    grasas: 6,
    unidadMedida: 'gramo',
    grupoId: 24,
  },
  {
    nombre: 'Alfajor de maicena (casero)',
    cantidad: 1,
    calorias: 150,
    proteinas: 2,
    carbohidratos: 22,
    grasas: 6,
    unidadMedida: 'unidad',
    grupoId: 24,
  },
  {
    nombre: 'Pastelitos de membrillo / batata',
    cantidad: 1,
    calorias: 220,
    proteinas: 3,
    carbohidratos: 30,
    grasas: 10,
    unidadMedida: 'unidad',
    grupoId: 24,
  },
  {
    nombre: 'Empanada de humita',
    cantidad: 1,
    calorias: 220,
    proteinas: 6,
    carbohidratos: 24,
    grasas: 11,
    unidadMedida: 'unidad',
    grupoId: 24,
  },

  // ========== GRUPO 25: Platos de restaurante y rotisería ==========
  {
    nombre: 'Milanesa completa (con papas fritas)',
    cantidad: 1,
    calorias: 700,
    proteinas: 35,
    carbohidratos: 45,
    grasas: 40,
    unidadMedida: 'unidad',
    grupoId: 25,
  },
  {
    nombre: 'Parrillada completa (porci\u00f3n)',
    cantidad: 100,
    calorias: 280,
    proteinas: 25,
    carbohidratos: 1,
    grasas: 20,
    unidadMedida: 'gramo',
    grupoId: 25,
  },
  {
    nombre: 'Asado de tira (porción cocida)',
    cantidad: 100,
    calorias: 290,
    proteinas: 23,
    carbohidratos: 0,
    grasas: 22,
    unidadMedida: 'gramo',
    grupoId: 25,
  },
  {
    nombre: 'Empanada de carne (rotisería)',
    cantidad: 1,
    calorias: 220,
    proteinas: 10,
    carbohidratos: 22,
    grasas: 11,
    unidadMedida: 'unidad',
    grupoId: 25,
  },
  {
    nombre: 'Empanada de pollo (rotisería)',
    cantidad: 1,
    calorias: 200,
    proteinas: 9,
    carbohidratos: 22,
    grasas: 9,
    unidadMedida: 'unidad',
    grupoId: 25,
  },
  {
    nombre: 'Suprema Maryland (pollo rebozado, huevo, papas)',
    cantidad: 1,
    calorias: 600,
    proteinas: 30,
    carbohidratos: 40,
    grasas: 35,
    unidadMedida: 'unidad',
    grupoId: 25,
  },
  {
    nombre: 'Bife de chorizo con guarnición (restaurante)',
    cantidad: 1,
    calorias: 500,
    proteinas: 40,
    carbohidratos: 15,
    grasas: 30,
    unidadMedida: 'unidad',
    grupoId: 25,
  },
  {
    nombre: 'Pizza napolitana (porción, restaurante)',
    cantidad: 1,
    calorias: 320,
    proteinas: 14,
    carbohidratos: 32,
    grasas: 15,
    unidadMedida: 'unidad',
    grupoId: 25,
  },

  // ========== GRUPO 26: Suplementos deportivos ==========
  {
    nombre: 'Whey protein (vainilla - ENA / Star Nutrition)',
    cantidad: 100,
    calorias: 380,
    proteinas: 80,
    carbohidratos: 7,
    grasas: 4,
    unidadMedida: 'gramo',
    grupoId: 26,
  },
  {
    nombre: 'Whey protein (chocolate - ENA / Star Nutrition)',
    cantidad: 100,
    calorias: 385,
    proteinas: 78,
    carbohidratos: 8,
    grasas: 4.5,
    unidadMedida: 'gramo',
    grupoId: 26,
  },
  {
    nombre: 'Whey protein (sin sabor - Star Nutrition)',
    cantidad: 100,
    calorias: 370,
    proteinas: 85,
    carbohidratos: 2,
    grasas: 3,
    unidadMedida: 'gramo',
    grupoId: 26,
  },
  {
    nombre: 'Creatina monohidrato (Star Nutrition / ENA)',
    cantidad: 100,
    calorias: 0,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 0,
    unidadMedida: 'gramo',
    grupoId: 26,
  },
  {
    nombre: 'BCAA 2:1:1 (Star Nutrition)',
    cantidad: 100,
    calorias: 380,
    proteinas: 95,
    carbohidratos: 0,
    grasas: 0,
    unidadMedida: 'gramo',
    grupoId: 26,
  },
  {
    nombre: 'Barra proteica 30g protein (MaxSport / ENA)',
    cantidad: 1,
    calorias: 220,
    proteinas: 30,
    carbohidratos: 18,
    grasas: 4,
    unidadMedida: 'unidad',
    grupoId: 26,
  },
  {
    nombre: 'Gel energético (illegal / ENA)',
    cantidad: 1,
    calorias: 90,
    proteinas: 0,
    carbohidratos: 22,
    grasas: 0,
    unidadMedida: 'unidad',
    grupoId: 26,
  },
  {
    nombre: 'Maltodextrina (Star Nutrition)',
    cantidad: 100,
    calorias: 380,
    proteinas: 0,
    carbohidratos: 95,
    grasas: 0,
    unidadMedida: 'gramo',
    grupoId: 26,
  },
];
