export enum EstadoTurno {
  PENDIENTE = 'PENDIENTE',
  CONFIRMADO = 'CONFIRMADO',
  PRESENTE = 'PRESENTE',
  EN_CURSO = 'EN_CURSO',
  CANCELADO = 'CANCELADO',
  REALIZADO = 'REALIZADO',
  AUSENTE = 'AUSENTE',
  REPROGRAMADO = 'REPROGRAMADO',
  BLOQUEADO = 'BLOQUEADO',
}
