export enum EstadoTurno {
  PROGRAMADO = 'PROGRAMADO',
  CONFIRMADO = 'CONFIRMADO',
  PRESENTE = 'PRESENTE',
  EN_CURSO = 'EN_CURSO',
  REALIZADO = 'REALIZADO',
  CANCELADO = 'CANCELADO',
  AUSENTE = 'AUSENTE',
}
